#!/bin/sh
# ** (c) 2017-19 TosoBoso - common lib for Kopano-4-Synology in Docker container
# ** set environment
# Image tags: Default is from 28.11./13.12.2018 and Migration from 15.12./15.12.2017
DEFAULT_TAG="Core-8.6.9.0_Webapp-3.5.0_Z-Push-2.5.0_WMeet-0.29.5"
MIGRATION_TAG="Core-8.4.5.0_Webapp-3.4.2_Z-Push-2.4.5"
SUPPORTED_TAG="Core-8.7.5_Webapp-3.5.8_Z-Push-2.5.0_WMeet-0.29.5"
COMMUNITY_TAG="Core-8.7.82_Webapp-3.5.8_Z-Push-2.5.0_WMeet-0.29.5"
DEFAULT_SIZE=158
MIGRATION_SIZE=143
SUPPORTED_SIZE=172
COMMUNITY_SIZE=172
RELEASE="Stable"
PHP_VER="7.0"
PKG_NAME=Kopano4s
ETC_PATH="/usr/syno/etc/packages/$PKG_NAME"
TARGET_PATH="/var/packages/$PKG_NAME/target"
UI_PATH="/usr/syno/synoman/webman/3rdparty"
LOG="$TARGET_PATH/log/package.log"
MYSQL="/usr/local/mariadb10/bin/mysql"
# ** download areas
K_URL_COM="download.kopano.io/community"
K_URL_SUP="download.kopano.io/supported"
K_DHUB="hub.docker.com/r/tosoboso/kopano4s/tags/"
# ** to make it work in test modus set pkg-name, log, wiz-switches testing for empty with ! -n
if [ -z "$SYNOPKG_PKGNAME" ]
then
	SYNOPKG_PKGNAME="$PKG_NAME"
fi
if [ -z "$SYNOPKG_TEMP_LOGFILE" ]
then
	SYNOPKG_TEMP_LOGFILE="$PKG_NAME.log"
fi
if [ -z "$SYNOPKG_PKG_STATUS" ]
then
	#SYNOPKG_PKG_STATUS="UPGRADE"
	SYNOPKG_PKG_STATUS="INSTALL"
fi
# ** for testing without GUI set wizz-values
if [ -z "$PKGWIZ_DB_NAME" ]
then
	# mark no-gui as manual and fill al defaults from package wizzard
	PKGWIZ_NO_GUI="true"
	PKGWIZ_K_DEF="true"
	PKGWIZ_K_SUP="false"
	PKGWIZ_K_COM="false"
	PKGWIZ_K_MIG="false"
	PKGWIZ_DB_NAME="kopano"
	PKGWIZ_K_SHARE="/volume1/kopano"
	PKGWIZ_K_BACKUP="/volume1/kopano/backup"
	PKGWIZ_K_SNR="1"
	PKGWIZ_HTTP_PORT_PREFIX=9000
	PKGWIZ_ICAL_PORT_PREFIX=8000
	IMAP_PORT=143
	IMAPS_PORT=993
	PKGWIZ_WRTC_PORT=8090
	PKGWIZ_TLS_SERVER_NAME="mail.mydomain.me"
	PKGWIZ_SMTPD_TLS="false"
	PKGWIZ_RPROXY="true"
	PKGWIZ_CONF_CHAT="false"
	PKGWIZ_FILES_DOC="false"
	PKGWIZ_COTURN="false"
	PKGWIZ_BUILD="false"
	PKGWIZ_ATTACHMENT_ON_FS="false"

	PKGWIZ_MAIL_DOMAINS="mail.mydomain.me"
	PKGWIZ_ALIAS_SYS=""
	PKGWIZ_RELAY_SERVER=""
	PKGWIZ_RELAY_USER=""
	PKGWIZ_RELAY_PWD=""
	PKGWIZ_SPAM_HELO="false"
	PKGWIZ_SPAM_RBL="false"
	PKGWIZ_K_AMAVISD="false"
	PKGWIZ_K_POSTGREY="false"
	PKGWIZ_BLOCK_ATTACHMENTS="bat|com|cpl|dll|exe|hta|js|pif|scr|vbs"
	PKGWIZ_MAX_MSG_SIZE=15

	PKGWIZ_LANG_EN="false"
	PKGWIZ_LANG_DE="false"
	PKGWIZ_LANG_FR="true"
	PKGWIZ_LANG_ES="false"
	PKGWIZ_LANG_IT="false"
	PKGWIZ_LANG_NL="false"

	PKGWIZ_RMASTER="false"
	PKGWIZ_TUNING_BUFFER_0="true"
	PKGWIZ_TUNING_BUFFER_20="false"
	PKGWIZ_TUNING_BUFFER_40="false"
	PKGWIZ_TUNING_BUFFER_60="false"
fi

# *** sub-routines common tooling ***
LOG_MESSAGE()
{
	local TS
	TS=$(date "+%Y.%m.%d-%H:%M:%S")
	echo "$TS $1" >> "$LOG"
}
GUI_MESSAGE()
{
	echo "$1" >> "$SYNOPKG_TEMP_LOGFILE"
}
NOTIFY_MESSAGE()
{
	# ** set the notify recipient best what can be found
	local RCP
	RCP="$SYNOPKG_USERNAME"
	if [ -z "$RCP" ]
	then
		RCP="$SYNO_WEBAPI_USERNAME"
	fi
	if [ -z "$RCP" ]
	then
		RCP="$USERNAME"
	fi
	if [ -z "$RCP" ]
	then
		RCP="$USER"
	fi
	if [ -z "$RCP" ] ||  [ "$RCP" = "root" ]
	then 
		RCP="@administrators"
	fi
	/usr/syno/bin/synodsmnotify "$RCP" "Kopano4s" "$1"
}
LEFT_HAND_SIDE()
{
	# ** ensure string in double quotes and seperator with single quotes due to space
	local STR
	STR="$1"
	local SEP
	SEP="$2"
	case $STR in
		(*"$SEP"*)
		LHS=${STR%%"$SEP"*}
		;;
		(*)
		LHS=$STR
		;;
	esac
	echo "$LHS"
	# ** to get right hand side RHS=${STR#*"$SEP"}
	# ** to get last char LCHAR=${STR#${STR%?}}
	# ** to get first char FCHAR=${STR%${STR#?}}
}
CHECK_DOWNLOAD_SOURCE()
{
	local URL
	URL="$1"
	if curl -Is "$URL" | head -n 1 | grep -q OK
	then
		return 0
	else
		echo "URL $URL does not exist"
		return 1
	fi
}
# ** find if tag exists on docker hub repository url
CHECK_DOCKER_TAG()
{
	local URL
	URL="https://registry.hub.docker.com/v2/repositories/$1/tags/"
	local TAG
	TAG="$2"
	# ** check if the url is valid
	if ! curl -Is "$URL" | head -n 1 | grep -q OK
	then
		echo "URL $URL does not exist"
		return 1
	fi
	# ** grep tag out of js stream
	if [ -z "$TAG" ]
	then
		echo "tag $TAG is empty"
		return 1
	fi
	if curl --silent "$URL" | jq '."results"[]["name"]' | grep -q "$TAG"

	then
		#echo "Tag found $TAG"		
		return 0
	else
		#echo "Tag $TAG does not exist"
		return 1
	fi
}
SAVE_LOG_ETC()
{
	# ** save backup of istall-log, kopano-etc for reset option
	cp "$LOG" /tmp/k4spackage.log
	mkdir -p "$K_SHARE/backup/etc"
	cp -R -f "$ETC_PATH/kopano" "$K_SHARE/backup/etc"
	# remove legacy z-push in kopano-etc
	if [ -e "$K_SHARE/backup/etc/kopano/z-push" ] ; then rm -R "$K_SHARE/backup/etc/kopano/z-push" ; fi
}
RESTORE_LOG_ETC()
{
	cp /tmp/k4spackage.log "$LOG"
	if [ ! -e "$ETC_PATH/kopano" ]
	then
		cp -R -f "$K_SHARE/backup/etc/kopano" "$ETC_PATH"
	fi
}
# en/disable 3rdparty admin ui and web icons and remove the cycle softlink
ENABLE_UI()
{
	# sodtlink from ralpath of UI (e.g. /volume1/@appstore/Package/ui) to 3rdparty area
	local REAL_UI
	REAL_UI=$(realpath /var/packages/"$PKG_NAME"/target/ui)
	$SUDO ln -sf "$REAL_UI" "$UI_PATH/$PKG_NAME"
}
DISABLE_UI()
{
	# if softlink exists from 3rdparty-UI to package-target ui then remove it
	if [ -h "$UI_PATH/$PKG_NAME" ] ; then $SUDO rm "$UI_PATH/$PKG_NAME" ; fi
}
# *** sub-routines GET_ (WIZZARD_CFG / TUNING_PARAMS / K_DOWNLOAD_BY_TAG) ***
# get from INFO file if we have a stable or beta version
GET_BETA_STABLE()
{
	if [ -e /var/packages/Kopano4s/INFO ]
	then
		if grep -q "^report_url" /var/packages/Kopano4s/INFO
		then
			K_RELEASE="Beta"
		else
			K_RELEASE="Stable"
		fi
	else
		K_RELEASE="$RELEASE"
	fi
}
# get the selected edition via gui-wizzard; non selected is in the else tree
GET_WIZZARD_EDITION()
{
	if [ "$PKGWIZ_K_DEF" = "true" ]
	then
		K_EDITION="Default"
	else
		if [ "$PKGWIZ_K_SUP" = "true" ]
		then
			K_EDITION="Supported"
		else
			if [ "$PKGWIZ_K_MIG" = "true" ]
			then
				K_EDITION="Migration"
			else
				K_EDITION="Community"
			fi
		fi
	fi
}
GET_WIZZARD_SIZE()
{
	if { [ "$PKGWIZ_CONF_CHAT" = "true" ] || [ "$PKGWIZ_FILES_DOC" = "true" ]; } && [ "$PKGWIZ_K_MIG" = "false" ]
	then
		K_SIZE="FULL"
	else
		K_SIZE="BASE"
	fi
}
# used in preinst for GUI download % of docker pull helper tool (Wizz-Edition & Size was loaded)
GET_K4S_SIZE()
{
	case "$K_EDITION" in
		Default)
		K4S_SIZE=$DEFAULT_SIZE
		;;
		Migration)
		K4S_SIZE=$MIGRATION_SIZE
		;;
		Supported)
		K4S_SIZE=$SUPPORTED_SIZE
		;;
		Community)
		K4S_SIZE=$COMMUNITY_SIZE
		;;
	esac
}
GET_WIZZARD_CFG()
{
	# ** set defaults for non wizzard settings
	# Careful K_REPLICATION is set below for master and then set off
	K_REPLICATION_PWD=""
	K_SEARCH="OFF"
	K_MONITOR="OFF"
	K_POSTGREY="OFF"
	K_FETCHMAIL="OFF"
	K_BOUNCE_SPAM="OFF"
	# ** get all cfgs from PKG_WIZZARD and write to package.cfg file
	K_SHARE=$PKGWIZ_K_SHARE
	K_BACKUP_PATH="$K_SHARE/backup"
	K_SNR="$PKGWIZ_K_SNR"
	# antiquated and replaced HTTP_PORT=$(expr $PKGWIZ_HTTP_PORT_PREFIX + "80")
	HTTP_PORT=$((PKGWIZ_HTTP_PORT_PREFIX + 80))
	HTTPS_PORT=$((PKGWIZ_HTTP_PORT_PREFIX  + 443))
	WRTC_PORT=$PKGWIZ_WRTC_PORT
	ICAL_PORT=$((PKGWIZ_ICAL_PORT_PREFIX + 80))
	ICALS_PORT=$((PKGWIZ_ICAL_PORT_PREFIX + 443))
	# IMAP port currently not via pkwizzard so set default
	IMAP_PORT=143
	IMAPS_PORT=993
	if [ "$PKGWIZ_TLS_SERVER_NAME" != "mail.mydomain.me" ]
	then
		TLS_SERVER_NAME="$PKGWIZ_TLS_SERVER_NAME"
	fi
	DB_NAME="$PKGWIZ_DB_NAME"
	DB_USER="$PKGWIZ_DB_NAME"
	DB_PASS="$(openssl rand -base64 48 | sed 's,/,_,g')"
	DB_MPASS="$PKGWIZ_DB_PASSWD"
	# edition and size from wizzard is used in several places hence via function
	GET_WIZZARD_EDITION
	GET_WIZZARD_SIZE
	DOCKER_PATH="$(synoshare --get docker | grep $'\t Path' | sed 's/.*\[\(.*\)].*/\1/')"
	DOCKER_HOST=$(ip address show docker0 | grep inet | awk '{print $2}' | cut -f1 -d/ | head -n 1)
	if [ "$PKGWIZ_BUILD" = "true" ]
	then
		IMAGE_BUILD="ON"
	else
		IMAGE_BUILD="OFF"
	fi
	if [ "$PKGWIZ_DOCKER_NW_HOST" = "true" ]
	then
		DOCKER_NW="host"
	else
		DOCKER_NW="bridge"
	fi
	if [ "$PKGWIZ_K_SEARCH" = "true" ]
	then
		K_SEARCH="ON"
	else
		K_SEARCH="OFF"
	fi
	if [ "$PKGWIZ_K_GATEWAY_ICAL" = "true" ]
	then
		K_GATEWAY="ON"
		K_ICAL="ON"
	else
		K_GATEWAY="OFF"
		K_ICAL="OFF"
	fi
	if [ "$PKGWIZ_CONF_CHAT" = "true" ]
	then
		K_WEBMEETINGS="ON"
		K_PRESENCE="ON"
		K_MATTERMOST="ON"
	else
		K_WEBMEETINGS="OFF"
		K_PRESENCE="OFF"
		K_MATTERMOST="OFF"
	fi
	if [ "$PKGWIZ_FILES_DOC" = "true" ]
	then
		K_FILES="ON"
		K_DOCEDIT="ON"
	else
		K_FILES="OFF"
		K_DOCEDIT="OFF"
	fi
	if [ "$PKGWIZ_COTURN" = "true" ]
	then
		K_COTURN="ON"
		GUI_MESSAGE "Note coTURN (Traversal Using Relay NAT) is in experimental mode and needs config to run. Ensure STUN port 3478 is opened in firewall."
	else
		K_COTURN="OFF"
	fi
	if [ "$PKGWIZ_ATTACHMENT_ON_FS" = "true" ]
	then
		ATTACHMENT_ON_FS="ON"
	else
		ATTACHMENT_ON_FS="OFF"
	fi
	if [ "$PKGWIZ_K_SYNC_SYNOCERT" = "true" ]
	then
		K_SYNC_SYNOCERT="ON"
	else
		K_SYNC_SYNOCERT="OFF"
	fi
	if [ "$PKGWIZ_SMTPD_TLS" = "true" ]
	then
		SMTPD_TLS="ON"
	else
		SMTPD_TLS="OFF"
	fi
	if [ "$PKGWIZ_RPROXY" = "true" ]
	then
		REVERSE_PROXY="ON"
	else
		REVERSE_PROXY="OFF"
	fi
	if [ "$PKGWIZ_MAIL_DOMAINS" != "mail.mydomain.me" ]
	then
		MAIL_DOMAINS=$PKGWIZ_MAIL_DOMAINS
		# ** call with non_white_space_string
		NWSPACE_STR=${MAIL_DOMAINS// /}
		MY_DOMAIN=$( LEFT_HAND_SIDE "$NWSPACE_STR" ',' )
	else
		MAIL_DOMAINS="localmail.me"
		MY_DOMAIN="localmail.me"
	fi
	ALIAS_SYS="$PKGWIZ_ALIAS_SYS"
	RELAY_SERVER="$PKGWIZ_RELAY_SERVER"
	RELAY_USER="$PKGWIZ_RELAY_USER"
	RELAY_PWD="$PKGWIZ_RELAY_PWD"
	if [ "$PKGWIZ_SPAM_HELO" = "true" ]
	then
		SPAM_HELO="ON"
	else
		SPAM_HELO="OFF"
	fi
	if [ "$PKGWIZ_SPAM_RBL" = "true" ]
	then
		SPAM_RBL="ON"
	else
		SPAM_RBL="OFF"
	fi
	if [ "$PKGWIZ_K_AMAVISD" = "true" ]
	then
		K_AMAVISD="ON"
		K_CLAMAVD="ON"
		# keep K_SPAMD off and only enable by GUI as feature
		K_SPAMD="OFF"
	else
		K_AMAVISD="OFF"
		K_CLAMAVD="OFF"
		K_SPAMD="OFF"
	fi
	if [ "$PKGWIZ_K_POSTGREY" = "true" ]
	then
		K_POSTGREY="ON"
	else
		K_POSTGREY="OFF"
	fi
	BLOCK_ATTACHMENTS=$PKGWIZ_BLOCK_ATTACHMENTS
	MAX_MSG_SIZE=$PKGWIZ_MAX_MSG_SIZE
	if [ "$PKGWIZ_LANG_EN" = "true" ]
	then
		LOCALE="en_US.UTF-8"
	fi
	if [ "$PKGWIZ_LANG_DE" = "true" ]
	then
		LOCALE="de_DE.UTF-8"
	fi
	if [ "$PKGWIZ_LANG_FR" = "true" ]
	then
		LOCALE="fr_FR.UTF-8"
	fi
	if [ "$PKGWIZ_LANG_ES" = "true" ]
	then
		LOCALE="es_ES.UTF-8"
	fi
	if [ "$PKGWIZ_LANG_IT" = "true" ]
	then
		LOCALE="it_IT.UTF-8"
	fi
	if [ "$PKGWIZ_LANG_NL" = "true" ]
	then
		LOCALE="nl_NL.UTF-8"
	fi
	if [ "$PKGWIZ_RMASTER" = "true" ]
	then
		K_REPLICATION="MASTER"
	else
		K_REPLICATION="OFF"
	fi
	KEEP_BACKUPS=5
	NOTIFY="ON"
	# ** set the notify recipient best what can be found
	NOTIFYTARGET="$SYNOPKG_USERNAME"
	if [ -z "$NOTIFYTARGET" ] ; then NOTIFYTARGET="$SYNO_WEBAPI_USERNAME" ; fi
	if [ -z "$NOTIFYTARGET" ] ; then NOTIFYTARGET="$USERNAME" ; fi
	if [ -z "$NOTIFYTARGET" ] ; then NOTIFYTARGET="$USER" ; fi
	if [ -z "$NOTIFYTARGET" ] ||  [ "$NOTIFYTARGET" = "root" ] ; then NOTIFYTARGET="@administrators" ; fi
	K_ARCHIVE_IMAP="OFF"
}
# used in upgrade mode to read the package.cfg file
GET_PKG_CFG()
{
	source "$ETC_PATH/package.cfg"
}
# for community and supported dynamically evaluate release tag base on url
GET_K_DOWNLOAD_RELEASE_TAG()
{
	local URL="$1"
	local TAG="[[:graph:]]*${2}[[:graph:]]*"
	local MAJ_REL
	local DOWNL
	local DOWNL_FILE
	# get basename from download URL for tag (e.g. Debian_9) which is recognized in between double-brackets
	DOWNL=$(curl --silent "$URL" | grep -o "$TAG" | head -1 | cut -f2 -d \")
	DOWNL_FILE=$(basename "$DOWNL")
	if [ -n "$DOWNL_FILE" ]
	then
		# based on download file split off as major release only the 1st 3 secions on . delimiter
		MAJ_REL=$(echo "$DOWNL_FILE" | grep -o "$TAG" | grep -o "[0-9.]*" | head -1 | cut -f1-3 -d .)
		echo "$MAJ_REL"
	else
		echo ""
	fi
}
# returns in RET_URL download path to pattern like *debian9.0
GET_K_DOWNLOAD_BY_TAG()
{
	local URL="$1"
	local TAG="[[:graph:]]*${2}[[:graph:]]*"
	RET_URL=$(curl --silent "$URL" | grep -o "$TAG" | head -1 | cut -f2 -d \")
	if [ -n "$RET_URL" ]
	then
		if echo "$URL" | grep -q "serial"
		then
			# keep SNR out of return as this is process ad-hoc
			RET_URL="download.kopano.io$RET_URL"
		else
			RET_URL="https://download.kopano.io$RET_URL"
		fi
	fi
}
# get the release number from download files with pre and post tag
GET_DOWNLOAD_REL_NR()
{
	local URL="$1"
	local TAG="${2}[[:graph:]]*${3}"
	RET_REL=$(echo "$URL" | grep -o "$TAG" | grep -o "[0-9.]*" | head -1)
	# split off as major release only the 1st 3 secions on . delimiter
	set -f; IFS='.'
	set -- "$RET_REL"
	set +f; unset IFS
	RET_REL_MAJ="${1}.${2}.${3}"
}
GET_DOCKER_TAGS()
{
	# taken from http://www.googlinux.com/list-all-tags-of-docker-image/ skipping library 
	# e.g. curl --silent https://registry.hub.docker.com/v2/repositories/tosoboso/kopano4s/tags/ | jq '."results"[]["name"]'
	local URL="https://registry.hub.docker.com/v2/repositories/$1/tags/"
	echo "tags in $1:"
	curl --silent "$URL" | jq '."results"[]["name"]'
}
# ** find the latest tag on docker hub repository url
GET_DOCKER_TAG()
{
	if [ -z "$1" ]
	then
		echo "Repository argument empty"		
		return 1
	fi
	local URL="https://registry.hub.docker.com/v2/repositories/$1/tags/"
	if [ -z "$2" ]
	then
		echo "Edition tag is empty"		
		return 1
	fi
	if [ -z "$3" ]
	then
		echo "Section 1 vs. 2 / current vs. previous is empty"		
		return 1
	fi
	local EDTAG="${2}-[[:graph:]]*"
	# ** check if the url is valid
	# we grep for the tag in <> and then remove the signs; 1st > then <
	# if we get previous version tag aka sec is 2 we need to do another tail from retun list
	if [ "$3" = "previous" ]
	then
		RET_VER_TAG=$(curl --silent "$URL" | jq '."results"[]["name"]' | grep -o "$EDTAG" | head -2 | tail -1 | cut -f1 -d '"')
	else
		RET_VER_TAG=$(curl --silent "$URL" | jq '."results"[]["name"]' | grep -o "$EDTAG" | head -1 | cut -f1 -d '"')
	fi
	if [ -n "$RET_VER_TAG" ]
	then
		return 0
	else
		echo "Could not find latest tag to edition $2"
		return 1
	fi
}
# calls GET_DOCKER_TAG and sets latest tag from repository or by fallback the version as of spk date
GET_VER_TAG()
{
	local SEC="current"
	if [ -n "$1" ]
	then
		SEC="$1"
	fi
	# if no package cfg exist get edition from PKGWIZ during install
	if [ -z "$K_EDITION" ]
	then
		GET_WIZZARD_EDITION
	fi
	# no need to do GET_DOCKER_TAG for Migration edition
	if [ "$K_EDITION" = "Migration" ]
	then
		VER_TAG=M-${MIGRATION_TAG}
	fi
	if [ "$K_EDITION" = "Default" ]
	then
		if GET_DOCKER_TAG "tosoboso/kopano4s" "D" "$SEC"
		then
			# found latest or previous version so use it
			VER_TAG=$RET_VER_TAG
		else
			VER_TAG=D-${DEFAULT_TAG}
		fi
	fi
	if [ "$K_EDITION" = "Supported" ]
	then
		if GET_DOCKER_TAG "tosoboso/kopano4s" "S" "$SEC"
		then
			# found latest or previous version so use it
			VER_TAG=$RET_VER_TAG
		else
			VER_TAG=S-${SUPPORTED_TAG}
		fi
	fi
	if [ "$K_EDITION" = "Community" ]
	then
		if GET_DOCKER_TAG "tosoboso/kopano4s" "C" "$SEC"
		then
			# found latest or previous version so use it
			VER_TAG=$RET_VER_TAG
		else
			VER_TAG=C-${COMMUNITY_TAG}
		fi

	fi
}
# ** calculated the tuning for caches in kopano server and MySql
GET_TUNIG_PARAMS()
{
	# ** only greps memory 7 digits aka 1gb and more (even 1gb might be missed due to reserved mem)
	local MEM_TOTAL
	MEM_TOTAL=$(grep -i memtotal /proc/meminfo | grep -o "[0-9][0-9][0-9][0-9][0-9][0-9][0-9]")
	# ** now grep 6 digits total memory aka kb instead of gb
	if [ "$MEM_TOTAL" = "" ]
	then
		MEM_TOTAL=$(grep -i memtotal /proc/meminfo | grep -o "[0-9][0-9][0-9][0-9][0-9][0-9]")
	fi
	if [ "$MEM_TOTAL" != "" ] && [ "$MEM_TOTAL" -gt 700000 ]
	then
		SYNO_MEMG=$(($MEM_TOTAL / 1000000))
		if [ "$SYNO_MEMG" = "0" ]
		then
			# ** round up again to 1 a 0.8-0.9 mem factor
			SYNO_MEMG=1
		fi
		# ** first grab 7 digits as gb then grep 6 digits aka kb
		local MEM_FREE
		MEM_FREE=$(grep -i memfree /proc/meminfo | grep -o "[0-9][0-9][0-9][0-9][0-9][0-9][0-9]")
		local MEM_CACHED
		MEM_CACHED=$(grep -i cached /proc/meminfo | grep -o "[0-9][0-9][0-9][0-9][0-9][0-9][0-9]")
		if [ "$MEM_FREE" = "" ]
		then
			MEM_FREE=$(grep -i memfree /proc/meminfo | grep -o "[0-9][0-9][0-9][0-9][0-9][0-9]")
		fi
		if [ "$MEM_CACHED" = "" ]
		then
			MEM_CACHED=$(grep -i cached /proc/meminfo | grep -o "[0-9][0-9][0-9][0-9][0-9][0-9]")
		fi
		if [ "$MEM_FREE" != "" ] && [ "$MEM_CACHED" != "" ]
		then
			MEM_USABLE=$(($MEM_FREE + $MEM_CACHED))
		fi
	else
		# ** forget about tuning when synology has less 1gb mem
		SYNO_MEMG=0
	fi
	if [ "$PKGWIZ_TUNING_BUFFER_0" = "true" ]
	then
		TUNING_BUFFER=0
	fi
	if [ "$PKGWIZ_TUNING_BUFFER_20" = "true" ]
	then
		TUNING_BUFFER=20
	fi
	if [ "$PKGWIZ_TUNING_BUFFER_40" = "true" ]
	then
		TUNING_BUFFER=40
	fi
	if [ "$PKGWIZ_TUNING_BUFFER_60" = "true" ]
	then
		TUNING_BUFFER=60
	fi
	if [ $TUNING_BUFFER -gt 0 ]
	then
		if [ "$SYNO_MEMG" = "0" ]
		then
			TUNING_BUFFER=0
			GUI_MESSAGE "Tuning disabled as it requires 1GB+ install and respective free memory. "
		fi
	fi
	INNODB_BUFFER=16
	if [ "$TUNING_BUFFER" = "60" ]
	then
		# ** 588mb (602112kb) is size of buffers
		BUFFERS=$((602112 * $SYNO_MEMG))
		if [ "$MEM_USABLE" -gt "$BUFFERS" ]
		then
			INNODB_BUFFER=$((288 * $SYNO_MEMG))
		else
			# ** downgrade tuning buffer
			TUNING_BUFFER=40
		fi
	fi
	if [ "$TUNING_BUFFER" = "40" ]
	then
		# ** 389mb (398336kb) is size of buffers
		BUFFERS=$((398336 * $SYNO_MEMG))
		if [ $MEM_USABLE -gt $BUFFERS ]
		then
			INNODB_BUFFER=$((192 * $SYNO_MEMG))
		else
			# ** downgrade tuning buffer
			TUNING_BUFFER=20
		fi
	fi
	if [ "$TUNING_BUFFER" = "20" ]
	then
		# ** 195mb (196608kb) is size of buffers
		BUFFERS=$((196608 * $SYNO_MEMG))
		if [ "$MEM_USABLE" -gt "$BUFFERS" ]
		then
			INNODB_BUFFER=$((96 * $SYNO_MEMG))
		else
			# ** downgrade tuning buffer
			TUNING_BUFFER=10
			INNO_BUFFER=$((64 * $SYNO_MEMG))
		fi
	fi
}
# *** sub-routines Pre-checks in preinst ***
# ** check for conflicting packages and exist in preinst if pkg not stopped
PKG_PRE_CHECK()
{
	# ** verify Mail-Server, MailPlus-Server, Zarafa4h, Z-Push exists: exit if running and notify on migration
	if [ -e /var/packages/MailServer ]
	then
		GUI_MESSAGE "MailServer package detected which is in conflict with Kopano4s. It must be stopped and it is reccomended to remove it.  "
		if /var/packages/MailServer/scripts/start-stop-status status
		then
			exit 1
		fi
	fi
	if [ -e /var/packages/MailPlusServer ]
	then
		GUI_MESSAGE "MailPlusServer package detected which is in conflict with Kopano4s. It must be stopped and it is reccomended to remove it.  "
		if /var/packages/MailPlusServer/scripts/start-stop-status status
		then
			exit 1
		fi
	fi
	if [ -e /var/packages/Zarafa4home ]
	then
		GUI_MESSAGE "Legacy Zarafa4home package detected which is in conflict with Kopano4s. It must be stopped and it is reccomended to remove it.  "
		if /var/packages/Zarafa4home/scripts/start-stop-status status
		then
			exit 1
		fi
		if [ -e /usr/local/etc/nginx/conf.d/www.Zarafa4h.conf ]
		then
			GUI_MESSAGE "Removed z4h reverse proxy setting for webapp. "
			rm /usr/local/etc/nginx/conf.d/www.Zarafa4h.conf
		fi
	fi
	if [ -e /var/packages/Z-Push ]
	then
		GUI_MESSAGE "Legacy Z-Push package detected which is in conflict with Kopano4s. It must be stopped and it is reccomended to remove it.  "
		if /var/packages/Z-Push/scripts/start-stop-status status
		then
			exit 1
		fi
	fi
}
# ** verify downloads available for building container otherwise exit
DOWNL_PRE_CHECK()
{
	# get_ver_tag will also get the wizzard gfg, it can be called with parameter e.g. previous in other script
	GET_VER_TAG ""
	if [ "$K_EDITION" = "Supported" ] || [ "$K_EDITION" = "Default" ] 
	then
		if [ "$SYNOPKG_PKG_STATUS" != "UPGRADE" ]
		then
			K_SNR="$PKGWIZ_K_SNR"
		fi
		DOWNLOAD_SOURCE="https://serial:${K_SNR}@${K_URL_SUP}/core:/"
	else
		DOWNLOAD_SOURCE="https://$K_URL_COM/core:/"
	fi
	if [ "$PKGWIZ_BUILD" = "true" ]
	then
		if ! CHECK_DOWNLOAD_SOURCE "$DOWNLOAD_SOURCE"
		then
			GUI_MESSAGE "Fatal Build Error: Download unavailable $DOWNLOAD_SOURCE "
			if [ "$PKGWIZ_NO_GUI" = "true" ] ; then echo "Fatal Build Error: Download unavailable $DOWNLOAD_SOURCE" ; fi
			exit 1
		fi
	else
		# ** verify serial-nr if running in supported mode via download check
		if [ "$K_EDITION" = "Supported" ] && ! CHECK_DOWNLOAD_SOURCE "$DOWNLOAD_SOURCE"
		then
			GUI_MESSAGE "Fatal SNR Error: could not authenticate via Kopano download <${K_SNR}> "
			if [ "$PKGWIZ_NO_GUI" = "true" ] ; then echo "Fatal SNR Error: could not authenticate via Kopano download <${K_SNR}>" ; fi
			exit 1	
		fi
		# ** verify docker hub available for loading container otherwise exit
		if ! CHECK_DOWNLOAD_SOURCE "https://$K_DHUB/"
		then
			GUI_MESSAGE "Fatal Error: Docker-Hub unavailable $K_DHUB "
			if [ "$PKGWIZ_NO_GUI" = "true" ] ; then echo "Fatal Error: Docker-Hub unavailable $K_DHUB" ; fi
			exit 1
		fi	
		if ! CHECK_DOCKER_TAG tosoboso/kopano4s "$VER_TAG"
		then
			NOTIFY_MESSAGE "Warning: Tag $VER_TAG not found on Docker-Hub for tosoboso/kopano4s"
			if [ "$PKGWIZ_NO_GUI" = "true" ] ; then echo "Warning: Tag $VER_TAG not found on Docker-Hub for tosoboso/kopano4s" ; fi
			exit 0
		fi
	fi
}
# ** creating and executing in bg-mode time-out script for edge case when docker helper tool does not come back
SPIN_HELPER_TIMEOUT()
{
	printf "# TimeOut script to get out of synology docker loading loop" > /tmp/docker-helper-timeout.sh
	# via sed append new lines after last char to build the sh script
	sed -i "$ a #!/bin/sh" /tmp/docker-helper-timeout.sh
	sed -i "$ a DH_TIMER=0" /tmp/docker-helper-timeout.sh
	sed -i "$ a DH_RUNNING=1" /tmp/docker-helper-timeout.sh
	sed -i "$ a while [ \"\$DH_RUNNING\" -eq 1 ]; do" /tmp/docker-helper-timeout.sh
	sed -i "$ a 	sleep 10" /tmp/docker-helper-timeout.sh
	sed -i "$ a 	DH_TIMER=\$((\$DH_TIMER + 1))" /tmp/docker-helper-timeout.sh
	sed -i "$ a 	# ** time-out and kill after 12m = 10x60sec/10" /tmp/docker-helper-timeout.sh
	sed -i "$ a 	if [ \"\$DH_TIMER\" -gt 60 ] ; then" /tmp/docker-helper-timeout.sh
	sed -i "$ a 		DH_RUNNING=0" /tmp/docker-helper-timeout.sh
	sed -i "$ a 		pkill -f /var/packages/Docker/target/tool/helper" /tmp/docker-helper-timeout.sh
	sed -i "$ a 		touch /tmp/killed-k4s-docker-download" /tmp/docker-helper-timeout.sh
	sed -i "$ a 		if [ -e /tmp/install_progress_Kopano4s ] ; then rm /tmp/install_progress_Kopano4s ; fi" /tmp/docker-helper-timeout.sh
	sed -i "$ a 	fi" /tmp/docker-helper-timeout.sh
	sed -i "$ a 	if [ \"\$DH_TIMER\" -gt 6 ] && [ ! -e /tmp/install_progress_Kopano4s ] ; then DH_RUNNING=0 ; fi" /tmp/docker-helper-timeout.sh
	sed -i "$ a done" /tmp/docker-helper-timeout.sh
	chmod 700 /tmp/docker-helper-timeout.sh
	/tmp/docker-helper-timeout.sh &

}
# *** sub-routines INIT_ (LOG / ) ***
INIT_LOG()
{
	local TS
	TS=$(date "+%Y.%m.%d-%H:%M:%S")
	echo -e "$TS Starting Kopano-4-Synology install.." > $LOG
}
INIT_USR_GRP()
{
	local RAND_PWD
	RAND_PWD=$(uuidgen | cut -c-40)
	if ! grep -q kopano: /etc/passwd
	then
		# ** add kopano group and user to join root for access patterns to rc and log files
		synouser --add kopano "$RAND_PWD" "Daemon user for Kopano Groupware Suite" 1 "" 0
		LOG_MESSAGE "Added Kopano user to system in login disabled mode, random pwd (synouser cmd)"
	fi
	if ! grep -q kopano: /etc/group
	then
		synogroup --add kopano kopano root
		synogroup --descset kopano "Group Kopano for shared access to mounts log and rc files"
		LOG_MESSAGE "Added Kopano group to system for members root and kopano. Add other admins as needed.."
	fi
	if ! grep -q k4samavis: /etc/passwd
	then
		# ** add kopano group and user to join root for access patterns to rc and log files
		synouser --add k4samavis "$RAND_PWD" "Daemon user for Kopano anti-virus" 1 "" 0
		LOG_MESSAGE "Added k4samavis user to system in login disabled mode, random pwd (synouser cmd)"
	fi
}
INIT_UPDATE()
{
	# perform any inits of later realease missing in install by update mode
	if [ ! -e "$K_SHARE/z-push" ] ; then mkdir -p "$K_SHARE/z-push" && chmod 750 "$K_SHARE/z-push" ; fi
	if [ ! -e "$ETC_PATH/z-push" ] ; then mkdir -p "$ETC_PATH/z-push" && chmod 750 "$ETC_PATH/z-push" ; fi
	# etc-kopano-zpush moved to etc-z-push so remove it
	if [ -e "$ETC_PATH/kopano/z-push" ] && [ ! -h "$ETC_PATH/kopano/z-push" ]
	then
		rm -R "$ETC_PATH/kopano/z-push"
	fi
	ä change to new naming convention for z-push and webapp confs incl. pkugins
	if [ ! -e "$ETC_PATH/z-push/z-push.conf.php" ] ; then cp "$TARGET_PATH"/merge/z-push/* "$ETC_PATH"/z-push ; fi
	if [ ! -e "$ETC_PATH/kopano/webapp/webapp.conf.php" ] ; then mv "$ETC_PATH"/kopano/webapp/config.php "$ETC_PATH"/kopano/webapp/webapp.conf.php ; fi
	PDIR=$(find "$ETC_PATH"/kopano/webapp/config-* -maxdepth 0 | cut -d '-' -f2-)
	for P in $PDIR ; do mv "$ETC_PATH"/kopano/webapp/config-"${P}" "$ETC_PATH"/kopano/webapp/plg.conf-"${P}" ; done
	# adjust mdm to port 9080
	if [ -e "$ETC_PATH"/kopano/webapp/plg.conf-mdm.php ] && ! grep -q 9080 "$ETC_PATH"/kopano/webapp/plg.conf-mdm.php
	then
		sed -i -e "s~localhost~localhost:9080~" "$ETC_PATH"/kopano/webapp/plg.conf-mdm.php
	fi
	if ! grep -q k4samavis: /etc/passwd
	then
		# ** add kopano group and user to join root for access patterns to rc and log files
		local RAND_PWD
		RAND_PWD=$(uuidgen | cut -c-40)
		synouser --add k4samavis "$RAND_PWD" "Daemon user for Kopano anti-virus" 1 "" 0
		LOG_MESSAGE "Added k4samavis user to system in login disabled mode, random pwd (synouser cmd)"
		AUSRID=$(id -u k4samavis)
		echo -e "$AUSRID" > "$ETC_PATH/kopano/auid"
	fi
	# attachments on fs in sync with pkg-cfg as it was set wrong in earlier versions
	if grep "^attachment_storage" /etc/kopano/server.cfg | grep -q files
	then
		ATTACHMENT_ON_FS="ON"
	else
		ATTACHMENT_ON_FS="OFF"
	fi
	# disable coredump in server.log to avoid log warnings and issues
	if grep -q "#coredump_enabled" /etc/kopano/server.cfg
	then
		sed -i -e "s~#coredump_enabled.*~coredump_enabled = no~" /etc/kopano/server.cfg
		sed -i -e "s~#coredump_enabled.*~coredump_enabled = no~" /etc/kopano/server.cfg.init
	fi
	if ! grep -q x_real_ip /etc/kopano/web/kopano-web.conf
	then
		cp "$TARGET_PATH/merge/web/kopano-web.conf" /etc/kopano/web
		cp "$TARGET_PATH/merge/web/nginx.conf" /etc/kopano/web
	fi
	# disable surveyclient_interval as still to early for supported dition
	sed -i -e "s~^surveyclient_interval~#surveyclient_interval~" "$TARGET_PATH/merge/server.cfg.init"
	# init IMAP(S)_PORT by enabled when it did not exist aka is empty (-z)
	if [ -z "$IMAP_PORT" ] ; then IMAP_PORT=143 ; fi
	if [ -z "$IMAPS_PORT" ] ; then IMAPS_PORT=993 ; fi
	# init K_SEARCH by enabled when it did not exist aka is empty (-z)
	if [ -z "$K_SEARCH" ] ; then K_SEARCH="ON" ; fi
	# amavis now holds spamassasin and clamav in same directory and soft links are used in container
	if [ -e "$K_SHARE/spamassasin" ] ; then rm "$K_SHARE/spamassasin" ; fi
	if [ -e "$K_SHARE/clamav" ] ; then rm "$K_SHARE/clamav" ; fi
	if ! grep -q ^BOUNCE_SPAM_ENABLED $ETC_PATH/kopano/default ; then echo "BOUNCE_SPAM_ENABLED=no" >> "$ETC_PATH/kopano/default" ; fi
	if ! grep -q ^BOUNCE_SPAM_ENABLED $ETC_PATH/kopano/default.init ; then echo "BOUNCE_SPAM_ENABLED=no" >> "$ETC_PATH/kopano/default.init" ; fi
	if ! grep -q ^CLAMAVD_ENABLED $ETC_PATH/kopano/default ; then echo "CLAMAVD_ENABLED=no" >> "$ETC_PATH/kopano/default" ; fi
	if ! grep -q ^CLAMAVD_ENABLED $ETC_PATH/kopano/default.init ; then echo "CLAMAVD_ENABLED=no" >> "$ETC_PATH/kopano/default.init" ; fi
	if ! grep -q ^SPAMD_ENABLED "$ETC_PATH/kopano/default"
	then
		sed -i "$ a SPAMD_ENABLED=no" "$ETC_PATH/kopano/default"
		sed -i "$ a SPAMD_CONFIG=/etc/kopano/spamd.cfg" "$ETC_PATH/kopano/default"
		sed -i "$ a SPAMD_OPTS=\"\"" "$ETC_PATH/kopano/default"
	fi
	if ! grep -q ^SPAMD_ENABLED "$ETC_PATH/kopano/default.init"
	then 
		sed -i "$ a SPAMD_ENABLED=no" "$ETC_PATH/kopano/default.init"
		sed -i "$ a SPAMD_CONFIG=/etc/kopano/spamd.cfg" "$ETC_PATH/kopano/default.init"
		sed -i "$ a SPAMD_OPTS=\"\"" "$ETC_PATH/kopano/default.init"
	fi
}
# ** create kopano share with synotool if not exists plus and set specific acls
INIT_SHARE_ETC()
{
	if [ ! -e "$K_SHARE" ]
	then
		# ** --add sharename share_desc share_path user_list_na user_list_rw user_list_ro share_browsable adv_privilege
		synoshare --add kopano 'Kopano area for Docker volumes and backups' $K_SHARE @users @kopano @administrators 0 0
		synoacltool -add $K_SHARE group:kopano:allow:rwxpdDaARWc--:fd--
		# ** now create subfolders for mounts in standard unix way
		mkdir -p "$K_SHARE"/amavis
		mkdir -p "$K_SHARE"/amavis/export
		mkdir -p "$K_SHARE"/amavis/ham
		mkdir -p "$K_SHARE"/amavis/spam
		mkdir -p "$K_SHARE"/archive
		mkdir -p "$K_SHARE"/attachments
		mkdir -p "$K_SHARE"/backup
		mkdir -p "$K_SHARE"/log
		mkdir -p "$K_SHARE"/log/z-push
		mkdir -p "$K_SHARE"/postgrey
		mkdir -p "$K_SHARE"/run
		mkdir -p "$K_SHARE"/search
		mkdir -p "$K_SHARE"/spool
		mkdir -p "$K_SHARE"/z-push
		chown -R root.kopano "$K_SHARE"
		chmod 751 "$K_SHARE"
		chmod 750 "$K_SHARE"/amavis
		chmod 750 "$K_SHARE"/archive
		chmod 750 "$K_SHARE"/attachments
		chmod 750 "$K_SHARE"/backup
		chmod 771 "$K_SHARE"/log
		chmod 750 "$K_SHARE"/log/z-push
		chmod 750 "$K_SHARE"/postgrey
		chmod 750 "$K_SHARE"/run
		chmod 750 "$K_SHARE"/search
		chmod 750 "$K_SHARE"/spool
		chmod 750 "$K_SHARE"/z-push
	fi
	# ** create kopano etc area and set specific acls
	if [ ! -e "$ETC_PATH/kopano" ] ; then mkdir -p "$ETC_PATH/kopano" ; fi
	if [ ! -e "$ETC_PATH/z-push" ] ; then mkdir -p "$ETC_PATH/z-push" ; fi
	if [ ! -e "$ETC_PATH/kopano/custom" ] ; then mkdir -p "$ETC_PATH/kopano/custom" ; fi
	if [ ! -e "$ETC_PATH/kopano/postfix" ] ; then mkdir -p "$ETC_PATH/kopano/postfix" ; fi
	if [ ! -e "$ETC_PATH/kopano/ssl" ] ; then mkdir -p "$ETC_PATH/kopano/ssl" ; fi
	if [ ! -e "$ETC_PATH/kopano/web" ] ; then mkdir -p "$ETC_PATH/kopano/web" ; fi
	chown -R root.kopano "$ETC_PATH/kopano"
	find "$ETC_PATH/kopano" -type d -exec chmod 750 "{}" ";"
	chmod 751 "$ETC_PATH/kopano"
	chmod 751 "$ETC_PATH/z-push"
	chmod 751 "$ETC_PATH/kopano/custom"
	chmod 751 "$ETC_PATH/kopano/postfix"
	chmod 700 "$ETC_PATH/kopano/ssl"
	chmod 751 "$ETC_PATH/kopano/web"
}
INIT_DATABASE()
{
	LOG_MESSAGE "Creating database $DB_NAME owned by $DB_USER with random internal password"
	if [ "$PKGWIZ_NO_GUI" = "true" ] ; then echo "creating kopano database in cmd-line mode you have to pass the mysql root pwd.." ; fi
	SQL="FLUSH PRIVILEGES; CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS'; CREATE DATABASE IF NOT EXISTS \`$DB_NAME\` DEFAULT CHARACTER SET \`utf8\` COLLATE \`utf8_unicode_ci\`; GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'localhost';"
	#if [ "$PKGWIZ_NO_GUI" = "true" ] ; then echo "SQL: $SQL"; fi
	# ** use mysql binary of MariaDB-10
	$MYSQL -uroot -p"${DB_MPASS}" -e "$SQL" >/tmp/out.sql 2>&1
	ERR=$?
	if [ "$ERR" -eq 1 ]
	then
		RET=$(cat /tmp/out.sql)
		# ** maybe mysql root pwd is not set -wow!
		$MYSQL -uroot -p -e "$SQL" >/tmp/out.sql 2>&1
		ERR=$?
		if [ "$ERR" -eq 0 ]
		then
			LOG_MESSAGE "Warning: you are running with no root passord your mysql -wow! Change it using Synology MariaDb widget or phyMyAdmin."
			GUI_MESSAGE "Warning: you are running with no root passord your mysql -wow! Change it using Synology MariaDb widget or phyMyAdmin. "
		else
			echo "Error in SQL: $RET"
			LOG_MESSAGE "Error creating database and owner (wrong root-pwd to MySQL?): $RET on SQL: $SQL"
			GUI_MESSAGE "Error creating database and owner (wrong root-pwd to MySQL?): $RET on SQL: $SQL"
			if [ "$PKGWIZ_NO_GUI" = "true" ] ; then echo "Error creating database and owner (wrong root-pwd to MySQL?): $RET on SQL: $SQL" ; fi
			# ** maybe user did still exist so drop him twice for clean install next time
			SQL_DROP_USR="DROP USER '$DB_USER'@'localhost';"
			$MYSQL -uroot -p"${DB_MPASS}" -e "$SQL_DROP_USR"
			ERR=$?
			if [ "$ERR" -eq 1 ]
			then
				# ** for our wow no pwd candidates
				$MYSQL -uroot -p -e "$SQL_DROP_USR"
			fi
			exit 1
		fi
	fi
}
# ** init acls for synology area run every time as it will be overwritten by upgrades
INIT_SYNOACL()
{
	chown root.administrators "$ETC_PATH"
	chmod 751 "$ETC_PATH"
	chown root.kopano "$ETC_PATH"/kopano
	chmod 751 "$ETC_PATH"/kopano
	chown -R root.http "$ETC_PATH"/z-push
	chmod 751 "$ETC_PATH"/z-push
	chmod 640 "$ETC_PATH"/z-push/*
	chown root.administrators "$ETC_PATH"/package.cfg
	chmod 640 "$ETC_PATH"/package.cfg
	chown http.http "$K_SHARE"/z-push
	chmod 770 "$K_SHARE"/z-push
	chown -R root.administrators /var/packages/Kopano4s/scripts/
	chmod 750 /var/packages/Kopano4s/scripts
	chmod 750 /var/packages/Kopano4s/scripts/*
	chown -R root.administrators "$TARGET_PATH"/log
	chmod 640 "$TARGET_PATH"/log/*.log
	chown -R root.administrators "$TARGET_PATH"/merge
	find "$TARGET_PATH"/merge -type f -exec chmod 640 "{}" ";"
	find "$TARGET_PATH"/merge -type d -exec chmod 750 "{}" ";"
	# restricting access to UI makes icons vanish and index.cgi is secure by auth-login check so no chmod
}
# ** init phase docker post build
INIT_DOCKER()
{
	# give init chance to complete
	INIT_TIMER=0
	INIT_RUNNING=1
	while [ "$INIT_RUNNING" -eq 1 ]
	do
		sleep 1
		INIT_TIMER=$(($INIT_TIMER + 1))
		if [ "$INIT_TIMER" -gt 30 ]
		then
			INIT_RUNNING=0
		fi
		if [ "$INIT_TIMER" -gt 3 ] && [ ! -e /etc/kopano4s/init.run ]
		then
			INIT_RUNNING=0
		fi
	done
	sleep 5
	INIT_TIMER=$(($INIT_TIMER + 5))
	MSG="Init done in $INIT_TIMER sec"
	if [ -n "$SUDO" ]
	then
		echo "$MSG"
	else
		LOG_MESSAGE "$MSG"
	fi
	$SUDO /var/packages/Kopano4s/scripts/wrapper/kopano-postfix.sh map /etc/kopano/postfix/valiases
	$SUDO /var/packages/Kopano4s/scripts/wrapper/kopano-postfix.sh map /etc/kopano/postfix/recipient_bcc
	$SUDO /var/packages/Kopano4s/scripts/wrapper/kopano-postfix.sh map /etc/kopano/postfix/sender_bcc
	$SUDO /var/packages/Kopano4s/scripts/wrapper/kopano-postfix.sh map /etc/kopano/postfix/recipient_access
	$SUDO /var/packages/Kopano4s/scripts/wrapper/kopano-postfix.sh map /etc/kopano/postfix/sender_access
}
# *** sub-routines SET_ (CFG_OPTIONS / GUI_NO_DEBUG / OPTIONALS / PKG_CFG / DOCKERFILE / DOCKER_ENV / SOFTLINKS) ***
# ** set options as per install wizzard GUI, Syno UID, DB usr, pwd
SET_CFG_OPTIONS()
{
	sed -i -e "s~kopano_db_name~$DB_NAME~" "$TARGET_PATH"/merge/server.cfg.init
	sed -i -e "s~kopano_db_user~$DB_USER~" "$TARGET_PATH"/merge/server.cfg.init
	sed -i -e "s~kopano_db_pwd~$DB_PASS~" "$TARGET_PATH"/merge/server.cfg.init
	# special case migration version 8.4.5 with old zcp server.cfg settings
	if [ "$K_EDITION" = "Migration" ]
	then
		sed -i -e "s~^server_listen = \*:236~#server_listen = \*:236\nserver_tcp_enabled = yes\nserver_tcp_port = 236~" "$TARGET_PATH"/merge/server.cfg.init
		sed -i -e "s~^server_listen_tls~#server_listen_tls~" "$TARGET_PATH"/merge/server.cfg.init
		sed -i -e "s~^surveyclient_interval~#surveyclient_interval~" "$TARGET_PATH"/merge/server.cfg.init
	fi
	# ** update user and group id which has 5 digits in init script
	KUSRID=$(id -u kopano)
	AUSRID=$(id -u k4samavis)
	GRPID=$(id -G kopano | grep -o "[0-9][0-9][0-9][0-9][0-9]")
	echo -e "$KUSRID" > "$ETC_PATH"/kopano/kuid
	echo -e "$GRPID" > "$ETC_PATH"/kopano/kgid
	echo -e "$AUSRID" > "$ETC_PATH"/kopano/auid
	# copy over base license if SNR exists
	if [ -n "$K_SNR" ]
	then
		mkdir -p "$ETC_PATH/kopano/license"
		echo -e "$K_SNR" > "$ETC_PATH"/kopano/license/base
	fi
	if [ "$ATTACHMENT_ON_FS" = "ON" ]
	then
		sed -i -e "s~attachment_storage.*~attachment_storage	= files~" "$TARGET_PATH"/merge/server.cfg.init
		if [ "$K_EDITION" = "Migration" ]
		then
			GUI_MESSAGE "Note attachment seetings need to be setup from scratch. When importing old Zarafa database with attachments on FS the strict mode will force no startup. See admin-manual regarding migration."
		fi
	fi
	if [ -n "$RELAY_SERVER" ]
	then
		echo "$RELAY_SERVER	$RELAY_USER:$RELAY_PWD" > "$TARGET_PATH/merge/postfix/sasl_passwd"
		sed -i -e "s~#relayhost = smtp.example.com~relayhost = $RELAY_SERVER~" "$TARGET_PATH/merge/postfix/main.cf"
		sed -i -e "s~#smtp_sasl_~smtp_sasl_~g" "$TARGET_PATH/merge/postfix/main.cf"
		sed -i -e "s~#smtp_use_tls~smtp_use_tls~" "$TARGET_PATH/merge/postfix/main.cf"
		sed -i -e "s~#smtp_smtp_tls_~smtp_smtp_tls_~g" "$TARGET_PATH/merge/postfix/main.cf"
	fi
	if [ "$SMTPD_TLS" = "ON" ]
	then
		sed -i -e "s~#smtpd_use_tls~smtpd_use_tls~" "$TARGET_PATH/merge/postfix/main.cf"
		sed -i -e "s~#tls_random_source~tls_random_source~" "$TARGET_PATH/merge/postfix/main.cf"
		sed -i -e "s~#smtpd_tls_~smtpd_tls_~g" "$TARGET_PATH/merge/postfix/main.cf"
	fi
	if [ "$SPAM_HELO" = "ON" ]
	then
		sed -i -e "s~#smtpd_helo_restrictions~smtpd_helo_restrictions~" "$TARGET_PATH/merge/postfix/main.cf"
	fi
	if [ "$SPAM_RBL" = "ON" ]
	then
		sed -i -e "s~#reject_rbl_client~ reject_rbl_client~g" "$TARGET_PATH/merge/postfix/main.cf"
	fi
	if [ "$K_AMAVISD" = "ON" ]
	then
		# ** uncomment the prepared content-filter and add dagent cfg for spam
		sed -i -e "s~#content_filter =~content_filter =~" "$TARGET_PATH/merge/postfix/main.cf"
		sed -i -e "s~spam_header_name = X-Spam-Status~spam_header_name = X-Spam-Flag~" "$TARGET_PATH/merge/dagent.cfg.init"
		sed -i -e "s~spam_header_value = Yes,~spam_header_value = Yes~" "$TARGET_PATH/merge/dagent.cfg.init"
	fi
	if [ "$K_POSTGREY" = "ON" ]
	then
		sed -i -e "s~#check_policy_service ~check_policy_service " "$TARGET_PATH/merge/postfix/main.cf"
	fi
	# ** update docker or chroot-build script and init files with services and set extra locales
	# ** replace mydomain.me by real in section mydomain and myhostname
	if [ -n "$MY_DOMAIN" ]
	then
		sed -i -e "s~mydomain.me~${MY_DOMAIN}~g" "$TARGET_PATH/merge/postfix/main.cf"
	fi
	if [ -n "$MY_DOMAIN" ]
	then
		sed -i -e "s~mydomain.me~${MY_DOMAIN}~g" "$TARGET_PATH/merge/postfix/main.cf"
	fi
	if [ -n "$TLS_SERVER_NAME" ]
	then
		sed -i -e "s~myhostname =.*~myhostname = ${TLS_SERVER_NAME}~" "$TARGET_PATH/merge/postfix/main.cf"
	fi
	hostname > "$TARGET_PATH/merge/postfix/hostname"
	sed -i -e "s~bat|com~$BLOCK_ATTACHMENTS~" "$TARGET_PATH/merge/postfix/header_checks"
	echo "$MAIL_DOMAINS" > "$TARGET_PATH/merge/postfix/vdomains"
	if [ -z "$ALIAS_SYS" ]
	then
		echo "postmaster@${MY_DOMAIN}	$ALIAS_SYS" > "$TARGET_PATH/merge/postfix/valiases"
		echo "root@${MY_DOMAIN}	$ALIAS_SYS" >> "$TARGET_PATH/merge/postfix/valiases"
		echo "admin@${MY_DOMAIN}	$ALIAS_SYS" >> "$TARGET_PATH/merge/postfix/valiases"
	fi
	cp -f $TARGET_PATH/merge/postfix/* "$ETC_PATH/kopano/postfix"
	# ** set webserver environment like port or reverse proxy directory
	if [ "$REVERSE_PROXY" = "ON" ]
	then
		if [ "$HTTP_PORT" != "9443" ]
		then
			sed -i -e "s~9443~$HTTPS_PORT~" "$TARGET_PATH/merge/web/www.Kopano4s.conf"
		fi
		if [ "$WRTC_PORT" != "8090" ]
		then
			sed -i -e "s~8090~$WRTC_PORT~" "$TARGET_PATH/merge/web/www.Kopano4s.conf"
		fi
		cp -f "$TARGET_PATH/merge/web/www.Kopano4s.conf" /usr/local/etc/nginx/conf.d
		nginx -s reload
		/bin/sed -i -e "s~9443~443~" "$TARGET_PATH/ui/config"
		/bin/sed -i -e 's~"url": "/",~"url": "/webapp/",~' "$TARGET_PATH/ui/config"
	else
		/bin/sed -i -e "s~9443~$HTTPS_PORT~" "$TARGET_PATH/ui/config"
	fi
	# ** tuning of kopano server chaches according to memory size
	if [ "$TUNING_BUFFER" = "60" ]
	then
		ORG_CACHE="cache_cell_size				= 64M"
		NEW_CACHE="cache_cell_size				= 288M"
		sed -i -e "s~$ORG_CACHE~$NEW_CACHE~" "$TARGET_PATH/merge/server.cfg.init"
		ORG_CACHE="cache_object_size			= 4M"
		NEW_CACHE="cache_object_size			= 18M"
		sed -i -e "s~$ORG_CACHE~$NEW_CACHE~" "$TARGET_PATH/merge/server.cfg.init"
		ORG_CACHE="cache_indexedobject_size	= 8M"
		NEW_CACHE="cache_indexedobject_size	= 36M"
		sed -i -e "s~$ORG_CACHE~$NEW_CACHE~" "$TARGET_PATH/merge/server.cfg.init"
		LOG_MESSAGE "Tuning kopno cache-call from 16M to 192M. Also increased other z-caches"
	fi
	if [ "$TUNING_BUFFER" = "40" ]
	then
		ORG_CACHE="cache_cell_size				= 64M"
		NEW_CACHE="cache_cell_size				= 192M"
		sed -i -e "s~$ORG_CACHE~$NEW_CACHE~" "$TARGET_PATH/merge/server.cfg.init"
		ORG_CACHE="cache_object_size			= 4M"
		NEW_CACHE="cache_object_size			= 12M"
		sed -i -e "s~$ORG_CACHE~$NEW_CACHE~" "$TARGET_PATH/merge/server.cfg.init"
		ORG_CACHE="cache_indexedobject_size	= 8M"
		NEW_CACHE="cache_indexedobject_size	= 24M"
		sed -i -e "s~$ORG_CACHE~$NEW_CACHE~" "$TARGET_PATH/merge/server.cfg.init"
		LOG_MESSAGE "Tuning kopano chache-call from 16M to 128M. Also increased other z-caches"
	fi
	if [ "$TUNING_BUFFER" = "20" ]
	then
		# ** this equals the original kopano defaults; no tuning is 1/2 z-default
		ORG_CACHE="cache_cell_size				= 64M"
		NEW_CACHE="cache_cell_size				= 96M"
		sed -i -e "s~$ORG_CACHE~$NEW_CACHE~" "$TARGET_PATH/merge/server.cfg.init"
		ORG_CACHE="cache_object_size			= 4M"
		NEW_CACHE="cache_object_size			= 6M"
		sed -i -e "s~$ORG_CACHE~$NEW_CACHE~" "$TARGET_PATH/merge/server.cfg.init"
		ORG_CACHE="cache_indexedobject_size	= 8M"
		NEW_CACHE="cache_indexedobject_size	= 12M"
		sed -i -e "s~$ORG_CACHE~$NEW_CACHE~" "$TARGET_PATH/merge/server.cfg.init"
		LOG_MESSAGE "Tuning kopano chache-call from 16M to 64M."
	fi
	# ** copy over merge sections to kopano-etc
	cp -f "$TARGET_PATH"/merge/*.init "$ETC_PATH"/kopano
	cp "$TARGET_PATH"/merge/z-push/* "$ETC_PATH"/z-push
	cp "$TARGET_PATH"/merge/postfix/* "$ETC_PATH"/kopano/postfix
	cp -f "$TARGET_PATH"/merge/fetchmailrc "$ETC_PATH"/kopano
	cp -f "$TARGET_PATH"/merge/dpkg-add "$ETC_PATH"/kopano/custom
	cp -f "$TARGET_PATH"/merge/postbuild.sh "$ETC_PATH"/kopano/custom
	# web-config: nginx.conf and kopano-web.conf
	cp -f "$TARGET_PATH"/merge/web/* "$ETC_PATH"/kopano/web
	# ** todo in /etc/php5/fpm/php.ini: allow_url_fopen = Off, short_open_tag = On, upload_max_filesize=30M, post_max_size=31M 
	# ** todo in /etc/nginx/nginx.conf: client_max_body_size 12m; .htaccess topics for z-push state
}
# ** set isDebug to fals in gui index.cgi
SET_GUI_NO_DEBUG()
{
	sed -i -e "s~my \$isDebug = 1~my \$isDebug = 0~" "$TARGET_PATH"/ui/index.cgi
}
# ** set Beta on in case of community edition in INFO file even if originally stable version as per INFO 
SET_COMMUNITY_BETA()
{
	if [ "$K_EDITION" = "Community" ]
	then
		sed -i -e 's~#report_url~report_url~' /var/packages/Kopano4s/INFO
	fi
}
# ** set optional services will be used at install and via GUI / optionals script later
SET_OPTIONALS()
{
	# ** change kopano-etc-default entry to enable optional services
	if [ "$K_EDITION" = "Supported" ] ; then $SUDO sed -i -e 's~SUPPORTED.*~SUPPORTED=yes~' "$ETC_PATH"/kopano/default.init ; fi
	if [ "$K_SEARCH" = "OFF" ]
	then
		$SUDO sed -i -e 's~SEARCH_ENABLED.*~SEARCH_ENABLED=no~' "$ETC_PATH"/kopano/default.init
		if grep -q "^#search_enabled" $ETC_PATH/kopano/server.cfg.init ; then $SUDO sed -i -e 's~#search_enabled~search_enabled~' "$ETC_PATH"/kopano/server.cfg.init ; fi
		$SUDO sed -i -e 's~search_enabled.*~search_enabled = no~' "$ETC_PATH"/kopano/server.cfg.init
	fi
	if [ "$K_MONITOR" = "ON" ] ; then $SUDO sed -i -e 's~MONITOR_ENABLED.*~MONITOR_ENABLED=yes~' "$ETC_PATH"/kopano/default.init ; fi
	if [ "$K_GATEWAY" = "ON" ] ; then $SUDO sed -i -e 's~GATEWAY_ENABLED.*~GATEWAY_ENABLED=yes~' "$ETC_PATH"/kopano/default.init ; fi
	if [ "$K_ICAL" = "ON" ] ; then $SUDO sed -i -e 's~ICAL_ENABLED.*~ICAL_ENABLED=yes~' "$ETC_PATH"/kopano/default.ini ; fi
	if [ "$K_POSTGREY" = "ON" ] ; then $SUDO sed -i -e 's~POSTGREY_ENABLED.*~POSTGREY_ENABLED=yes~' "$ETC_PATH"/kopano/default.init ; fi
	if [ "$K_AMAVISD" = "ON" ] ; then $SUDO sed -i -e 's~AMAVISD_ENABLED.*~AMAVISD_ENABLED=yes~' "$ETC_PATH"/kopano/default.init ; fi
	if [ "$K_CLAMAVD" = "ON" ] ; then $SUDO sed -i -e 's~CLAMAVD_ENABLED.*~CLAMAVD_ENABLED=yes~' "$ETC_PATH"/kopano/default.init ; fi
	if [ "$K_SPAMD" = "ON" ] ; then $SUDO sed -i -e 's~SPAMD_ENABLED.*~SPAMD_ENABLED=yes~' "$ETC_PATH"/kopano/default.init ; fi
	if [ "$K_BOUNCE_SPAM" = "ON" ] ; then $SUDO sed -i -e 's~BOUNCE_SPAM_ENABLED.*~BOUNCE_SPAM_ENABLED=yes~' "$ETC_PATH"/kopano/default.init ; fi
	if [ "$K_FETCHMAIL" = "ON" ] ; then $SUDO sed -i -e 's~FETCHMAIL_ENABLED.*~FETCHMAIL_ENABLED=yes~' "$ETC_PATH"/kopano/default.init ; fi
	if [ "$K_ARCHIVE_IMAP" = "ON" ] ; then $SUDO sed -i -e 's~COURIER_IMAP_ENABLED.*~COURIER_IMAP_ENABLED=yes~' "$ETC_PATH"/kopano/default.init ; fi
	if [ "$K_WEBMEETINGS" = "ON" ] ; then $SUDO sed -i -e 's~WEBMEETINGS_ENABLED.*~WEBMEETINGS_ENABLED=yes~' "$ETC_PATH"/kopano/default.init ; fi
	if [ "$K_PRESENCE" = "ON" ] ; then $SUDO sed -i -e 's~PRESENCE_ENABLED.*~PRESENCE_ENABLED=yes~' "$ETC_PATH"/kopano/default.init ; fi
	if [ "$K_MATTERMOST" = "ON" ] ; then $SUDO sed -i -e 's~MATTERMOST_ENABLED.*~MATTERMOST_ENABLED=yes~' "$ETC_PATH"/kopano/default.init ; fi
	if [ "$K_COTURN" = "ON" ] ; then $SUDO sed -i -e 's~COTURN_ENABLED.*~COTURN_ENABLED=yes~' "$ETC_PATH"/kopano/default.init ; fi
	$SUDO cp "$ETC_PATH/kopano/default.init" "$ETC_PATH"/kopano/default
}
SET_K_CERTIFICATE()
{
	LOG_MESSAGE "Importing SSL certificates from synology default area to container for NGINX and Postfix"
	chmod 600 "$ETC_PATH"/kopano/ssl/*
	if [ -e /usr/syno/etc/certificate/system/default/fullchain.pem ]
	then
		cp /usr/syno/etc/certificate/system/default/fullchain.pem "$ETC_PATH"/kopano/ssl/svrcertbundle.pem
	else
		cp /usr/syno/etc/certificate/system/default/cert.pem "$ETC_PATH"/kopano/ssl/svrcertbundle.pem
	fi
	cp /usr/syno/etc/certificate/system/default/privkey.pem "$ETC_PATH"/kopano/ssl/server.key
	chmod 400 "$ETC_PATH"/kopano/ssl/*
}
SYNC_K_CERTIFICATE()
{
	if [ "$K_SYNC_SYNOCERT" = "ON" ] && $SUDO [ -e "$ETC_PATH/kopano/ssl/server.key" ]
	then
		if ! $SUDO diff -s "$ETC_PATH/kopano/ssl/server.key" /usr/syno/etc/certificate/system/default/privkey.pem | grep -q "identical"
		then
			echo "Importing Synology SSL certificates into Kopano container due to updated certs"
			LOG_MESSAGE "Importing Synology SSL certificates into Kopano container due to updated certs"
			if $SUDO [ -e /usr/syno/etc/certificate/system/default/fullchain.pem ]
			then
				$SUDO cp /usr/syno/etc/certificate/system/default/fullchain.pem "$ETC_PATH/kopano/ssl/svrcertbundle.pem"
			else
				$SUDO cp /usr/syno/etc/certificate/system/default/cert.pem "$ETC_PATH/kopano/ssl/svrcertbundle.pem"
			fi
			$SUDO cp /usr/syno/etc/certificate/system/default/privkey.pem "$ETC_PATH/kopano/ssl/server.key"
		fi
	fi
}
SET_K_LOCALE()
{
	# ** change kopano-etc-default entry for locales if non-en_US selected
	if [ "$LOCALE" != "en_US.UTF-8" ]
	then
		sed -i -e "s~KOPANO_LOCALE=\"C~KOPANO_LOCALE=\"$LOCALE~" $ETC_PATH/kopano/default.init
		sed -i -e "s~KOPANO_USERSCRIPT_LOCALE=\"C~KOPANO_USERSCRIPT_LOCALE=\"$LOCALE~" $ETC_PATH/kopano/default.init
	fi
}
SET_SQL_CONF()
{
	MYCF_CHG=0
	if [ ! -e  /var/packages/MariaDB10/etc/my.cnf ] ; then touch /var/packages/MariaDB10/etc/my.cnf ; fi
	if ! (grep -q "[mysqld]" /var/packages/MariaDB10/etc/my.cnf) ; then echo -e "[mysqld]" >> /var/packages/MariaDB10/etc/my.cnf ; fi
	# only set for non-existent master / slave as during active replication mysql will stop
	if [ "$K_REPLICATION" = "MASTER" ]
	then
		RHOST=$(hostname)
		if ! (grep -q "server-id" /var/packages/MariaDB10/etc/my.cnf) ; then MYCF_CHG=1 ; echo -e "server-id = 101" >> /var/packages/MariaDB10/etc/my.cnf ; fi
		if ! (grep -q "report-host" /var/packages/MariaDB10/etc/my.cnf) ; then MYCF_CHG=1 ; echo -e "report-host = $RHOST" >> /var/packages/MariaDB10/etc/my.cnf ;fi
		if ! (grep -q "log-bin" /var/packages/MariaDB10/etc/my.cnf) ; then MYCF_CHG=1 ; echo -e "log-bin" >> /var/packages/MariaDB10/etc/my.cnf ; fi
		if ! (grep -q "log_error" /var/packages/MariaDB10/etc/my.cnf) ; then MYCF_CHG=1 ; echo -e "log_error = mysqld-bin-log.err" >> /var/packages/MariaDB10/etc/my.cnf ; fi
		if ! (grep -q "binlog-format" /var/packages/MariaDB10/etc/my.cnf) ; then MYCF_CHG=1 ; echo -e "binlog-format = mixed" >> /var/packages/MariaDB10/etc/my.cnf ; fi
		if ! (grep -q "binlog_do_db" /var/packages/MariaDB10/etc/my.cnf) ; then MYCF_CHG=1 ; echo -e "binlog_do_db = $DB_NAME" >> /var/packages/MariaDB10/etc/my.cnf ; fi
		if ! (grep -q "sync_binlog" /var/packages/MariaDB10/etc/my.cnf) ; then MYCF_CHG=1 ; echo -e "sync_binlog = 1" >> /var/packages/MariaDB10/etc/my.cnf ; fi
		if ! (grep -q "expire_logs_days" /var/packages/MariaDB10/etc/my.cnf) ; then MYCF_CHG=1 ; echo -e "expire_logs_days = 5" >> /var/packages/MariaDB10/etc/my.cnf ; fi
		if ! (grep -q "innodb_flush_log_at_trx_commit" /var/packages/MariaDB10/etc/my.cnf) ; then MYCF_CHG=1 ; echo -e "innodb_flush_log_at_trx_commit = 1" >> /var/packages/MariaDB10/etc/my.cnf ; fi
		if ! (grep -q "max_allowed_packet" /var/packages/MariaDB10/etc/my.cnf) ; then MYCF_CHG=1 ; echo -e "max_allowed_packet = 16M" >> /var/packages/MariaDB10/etc/my.cnf ; fi
		sed -i -e "s~max_allowed_packet = 10M~max_allowed_packet = 16M~" /var/packages/MariaDB10/etc/my.cnf
		# replication prepared but not enabled
		K_REPLICATION="OFF"
	fi
	if [ "$TUNING_BUFFER" -gt 0 ] && ! (grep -q kopano4s /var/packages/MariaDB10/etc/my.cnf)
	then
		MYCF_CHG=1
		echo -e "#kopano4s overwrite default innodb_buffer as 16M" >> /var/packages/MariaDB10/etc/my.cnf
		echo -e "innodb_buffer_pool_size = ${INNODB_BUFFER}M" >> /var/packages/MariaDB10/etc/my.cnf
		# innodb_log_file_size should be 25% of buffer_pool_size but default has no setting
		LOG_MESSAGE "Tuning mysql innodb-chache from 16M to ${INNODB_BUFFER}M. Restarting MariaDB to make it effecive"
	fi
	if ! (grep -q "max_allowed_packet" /var/packages/MariaDB10/etc/my.cnf) ; then MYCF_CHG=1; echo -e "max_allowed_packet = 10M" >> /var/packages/MariaDB10/etc/my.cnf ; fi
	# restarting mariadb
	if [ $MYCF_CHG -gt 0 ]
	then
		/var/packages/MariaDB10/scripts/start-stop-status restart
	fi
}
SET_PKG_CFG()
{
	(
		echo DB_NAME="\"$DB_NAME\""
		echo DB_USER="\"$DB_USER\""
		echo DB_PASS="\"$DB_PASS\""
		echo K_SHARE="\"$K_SHARE\""
		echo K_EDITION="\"$K_EDITION\""
		echo K_SIZE="\"$K_SIZE\""
		echo K_RELEASE="\"$K_RELEASE\""
		echo K_SNR="\"$K_SNR\""
		echo K_BACKUP_PATH="\"$K_BACKUP_PATH\""
		echo HTTP_PORT=$HTTP_PORT
		echo HTTPS_PORT=$HTTPS_PORT
		echo WRTC_PORT=$WRTC_PORT
		echo ICAL_PORT=$ICAL_PORT
		echo ICALS_PORT=$ICALS_PORT
		echo IMAP_PORT=$IMAP_PORT
		echo IMAPS_PORT=$IMAPS_PORT
		echo DOCKER_PATH="\"$DOCKER_PATH\""
		echo DOCKER_HOST="\"$DOCKER_HOST\""
		echo DOCKER_NW="\"$DOCKER_NW\""
		echo IMAGE_BUILD="\"$IMAGE_BUILD\""
		echo K_SYNC_SYNOCERT="\"$K_SYNC_SYNOCERT\""
		echo K_REPLICATION="\"$K_REPLICATION\""
		echo K_REPLICATION_PWD="\"$K_REPLICATION_PWD\""
		echo K_SEARCH="\"$K_SEARCH\""
		echo K_MONITOR="\"$K_MONITOR\""
		echo K_GATEWAY="\"$K_GATEWAY\""
		echo K_ICAL="\"$K_ICAL\""
		echo K_ARCHIVE_IMAP="\"$K_ARCHIVE_IMAP\""
		echo K_POSTGREY="\"$K_POSTGREY\""
		echo K_FETCHMAIL="\"$K_FETCHMAIL\""
		echo K_WEBMEETINGS="\"$K_WEBMEETINGS\""
		echo K_PRESENCE="\"$K_PRESENCE\""
		echo K_MATTERMOST="\"$K_MATTERMOST\""
		echo K_COTURN="\"$K_COTURN\""
		echo K_FILES="\"$K_FILES\""
		echo K_DOCEDIT="\"$K_DOCEDIT\""
		echo K_SIZE="\"$K_SIZE\""
		echo ATTACHMENT_ON_FS="\"$ATTACHMENT_ON_FS\""
		echo TLS_SERVER_NAME="\"$TLS_SERVER_NAME\""
		echo SMTPD_TLS="\"$SMTPD_TLS\""
		echo REVERSE_PROXY="\"$REVERSE_PROXY\""
		echo MAIL_DOMAINS="\"$MAIL_DOMAINS\""
		echo MY_DOMAIN="\"$MY_DOMAIN\""
		echo ALIAS_SYS="\"$ALIAS_SYS\""
		echo SPAM_HELO="\"$SPAM_HELO\""
		echo SPAM_RBL="\"$SPAM_RBL\""
		echo K_BOUNCE_SPAM="\"$K_BOUNCE_SPAM\""
		echo K_AMAVISD="\"$K_AMAVISD\""
		echo K_CLAMAVD="\"$K_CLAMAVD\""
		echo K_SPAMD="\"$K_SPAMD\""
		echo K_POSTGREY="\"$K_POSTGREY\""
		echo MAX_MSG_SIZE="\"$MAX_MSG_SIZE\""
		echo BLOCK_ATTACHMENTS="\"$BLOCK_ATTACHMENTS\""
		echo LOCALE="\"$LOCALE\""
		echo KEEP_BACKUPS=$KEEP_BACKUPS
		echo NOTIFY="\"$NOTIFY\""
		echo NOTIFYTARGET="\"$NOTIFYTARGET\""
		echo SYNO_MEMG=$SYNO_MEMG
		echo TUNING_BUFFER=$TUNING_BUFFER
		echo INNODB_BUFFER=$INNODB_BUFFER
		echo VER_TAG="\"$VER_TAG\""
		echo INSTALL_STATE="$INSTALL_STATE"
	) > "$ETC_PATH"/package.cfg
}
# ** set all environment as docker mounts and ports exposed, do all via softlinks from etc
SET_DOCKER_ENV()
{
	# we are soft-linking the mounts in docker share via etc to deal with Synology Docker GUI issues (mounts "outside")
	# create soflinks from k-etc-docker-volumes to kopano-share for mounts into docker; create docker path for downloaded image case
	# to get the right localtime and timezone mount /etc/localtime & /etc/TZ in container
	$SUDO mkdir -p "$DOCKER_PATH/kopano4s"
	$SUDO ln -sf "$ETC_PATH/kopano" "$DOCKER_PATH/kopano4s/etc-kopano"
	$SUDO ln -sf "$ETC_PATH/z-push" "$DOCKER_PATH/kopano4s/etc-z-push"
	$SUDO ln -sf "$K_SHARE/amavis" "$DOCKER_PATH/kopano4s/amavis"
	$SUDO ln -sf "$K_SHARE/archive" "$DOCKER_PATH/kopano4s/archive"
	$SUDO ln -sf "$K_SHARE/attachments" "$DOCKER_PATH/kopano4s/attachments"
	$SUDO ln -sf "$K_SHARE/backup" "$DOCKER_PATH/kopano4s/backup"
	$SUDO ln -sf /etc/localtime "$DOCKER_PATH/kopano4s/localtime"
	$SUDO ln -sf "$K_SHARE/log" "$DOCKER_PATH/kopano4s/log"
	$SUDO ln -sf /run/mysqld "$DOCKER_PATH/kopano4s/mysocket"
	$SUDO ln -sf "$K_SHARE/postgrey" "$DOCKER_PATH/kopano4s/postgrey"
	$SUDO ln -sf "$K_SHARE/run" "$DOCKER_PATH/kopano4s/run"
	$SUDO ln -sf "$K_SHARE/run" /run/kopano
	$SUDO ln -sf "$K_SHARE/search" "$DOCKER_PATH/kopano4s/search"
	$SUDO ln -sf "$K_SHARE/spool" "$DOCKER_PATH/kopano4s/spool"
	$SUDO ln -sf /etc/TZ "$DOCKER_PATH/kopano4s/timezone"
	$SUDO ln -sf "$K_SHARE/z-push" "$DOCKER_PATH/kopano4s/z-push"
	# remove recursive softlinks kopano and z-push in etc, log, k-share
	if [ -e /etc/kopano/kopano ] && [ -h /etc/kopano/kopano ] ; then $SUDO rm /etc/kopano/kopano ; fi
	if [ -e /etc/kopano/z-push ] ; then $SUDO rm -R /etc/kopano/z-push ; fi
	if [ -e /etc/z-push/z-push ] && [ -h /etc/z-push/z-push ] ; then $SUDO rm /etc/z-push/z-push ; fi
	if [ -e "$K_SHARE/z-push/z-push" ] && [ -h "$K_SHARE/z-push/z-push" ] ; then $SUDO rm "$K_SHARE/z-push/z-push" ; fi
	if [ -e "$K_SHARE/run/run" ] && [ -h "$K_SHARE/run/run" ] ; then $SUDO rm "$K_SHARE/run/run" ; fi
	if [ -e /var/log/kopano/kopano ] && [ -h /var/log/kopano/kopano ] ; then $SUDO rm /var/log/kopano/kopano ; fi

	local K_ETC="$DOCKER_PATH/kopano4s/etc-kopano"
	local Z_ETC="$DOCKER_PATH/kopano4s/etc-z-push"
	local K_AMV="$DOCKER_PATH/kopano4s/amavis"
	local K_ARC="$DOCKER_PATH/kopano4s/archive"
	local K_ATC="$DOCKER_PATH/kopano4s/attachments"
	local K_BUP="$DOCKER_PATH/kopano4s/backup"
	local K_LT="$DOCKER_PATH/kopano4s/localtime"
	local K_LOG="$DOCKER_PATH/kopano4s/log"
	local M_SOCK="$DOCKER_PATH/kopano4s/mysocket"
	local K_GRY="$DOCKER_PATH/kopano4s/postgrey"
	local K_RUN="$DOCKER_PATH/kopano4s/run"
	local K_SRC="$DOCKER_PATH/kopano4s/search"
	local K_SPL="$DOCKER_PATH/kopano4s/spool"
	local K_TZ="$DOCKER_PATH/kopano4s/timezone"
	local K_ZPU="$DOCKER_PATH/kopano4s/z-push"

	DOCKER_MOUNTS="-v $M_SOCK:/run/mysqld:ro -v $K_RUN:/run/kopano -v $K_LT:/etc/localtime:ro -v $K_TZ:/etc/timezone:ro -v $K_ETC:/etc/kopano -v $Z_ETC:/etc/z-push \
	-v $K_AMV:/var/lib/amavis -v $K_ARC:/var/lib/kopano/archive -v $K_ATC:/var/lib/kopano/attachments -v $K_BUP:/var/lib/kopano/backup \
	-v $K_LOG:/var/log/kopano -v $K_GRY:/var/lib/postgrey -v $K_SRC:/var/lib/kopano/search -v $K_SPL:/var/spool/postfix -v $K_ZPU:/var/lib/z-push"
	K_HOST="kopano4s.$MY_DOMAIN"	
	DOCKER_PORTS="-p 236:236 -p 237:237 -p 25:25 -p 2003:2003 -p $HTTP_PORT:9080 -p $HTTPS_PORT:9443"
	if [ "$K_GATEWAY" = "ON" ]
	then
		DOCKER_PORTS="$DOCKER_PORTS -p $IMAP_PORT:143 -p $IMAPS_PORT:993"
	fi
	if [ "$K_ICAL" = "ON" ]
	then
		DOCKER_PORTS="$DOCKER_PORTS -p $ICAL_PORT:8080 -p $ICALS_PORT:8443"
	fi
	if [ "$K_ARCHIVE_IMAP" = "ON" ]
	then
		DOCKER_PORTS="$DOCKER_PORTS -p 144:144 -p 994:994"
	fi
	if [ "$K_WEBMEETINGS" = "ON" ]
	then
		DOCKER_PORTS="$DOCKER_PORTS -p $WRTC_PORT:8090 -p 1935:1935"
	fi
	if [ "$K_COTURN" = "ON" ]
	then
		DOCKER_PORTS="$DOCKER_PORTS -p 3478:3478"
	fi
	# we use --init for tine plus pass and overwrite the image LAG with our locale via -e
	DOCKER_PARAMS="-d --init --name kopano4s --hostname $K_HOST --restart=on-failure:3 -e PARENT=$DOCKER_HOST -e LANG=$LOCALE -e LANGUAGE=$LOCALE -e LC_ALL=$LOCALE"
	# special experimental feature network paramater host to be added to parameters
	if [ "$DOCKER_NW" = "host" ] && docker run --help | grep -q network ; then DOCKER_PARAMS="$DOCKER_PARAMS --network host" ; fi
	DOCKER_IMAGE="tosoboso/kopano4s:$VER_TAG"
}
# ** in case from upgrading migration version 8.4.5 change server.cfg tcp parameters 
SET_SVR_CFG_NEW()
{
	if [ "$K_EDITION" != "Migration" ]
	then
		if [ -e "$ETC_PATH/kopano/server.cfg.init" ] && grep -q server_listen "$ETC_PATH/kopano/server.cfg.init"
		then
			$SUDO sed -i -e "s~#server_listen~server_listen~" $ETC_PATH/kopano/server.cfg.init
			$SUDO sed -i -e "s~#server_listen_tls~server_listen_tls~" $ETC_PATH/kopano/server.cfg.init
			$SUDO sed -i -e "s~server_tcp_enabled~#server_tcp_enabled~" $ETC_PATH/kopano/server.cfg.init
			$SUDO sed -i -e "s~server_tcp_port~#server_tcp_port~" $ETC_PATH/kopano/server.cfg.init
		fi
		if [ -e $ETC_PATH/kopano/server.cfg ] && grep -q server_listen $ETC_PATH/kopano/server.cfg
		then
			$SUDO sed -i -e "s~#server_listen~server_listen~" $ETC_PATH/kopano/server.cfg
			$SUDO sed -i -e "s~#server_listen_tls~server_listen_tls~" $ETC_PATH/kopano/server.cfg
			$SUDO sed -i -e "s~server_tcp_enabled~#server_tcp_enabled~" $ETC_PATH/kopano/server.cfg
			$SUDO sed -i -e "s~server_tcp_port~#server_tcp_port~" $ETC_PATH/kopano/server.cfg
		fi
	fi
}
# ** set all softlinks and cleanup script file only used in container
SET_SOFTLINKS()
{
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-admin.sh /usr/local/bin/kopano-admin
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-autorespond.sh /usr/local/bin/kopano-autorespond
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-backup.sh /usr/local/bin/kopano-backup
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-cachestat.sh /usr/local/bin/kopano-cachestat
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-cli.sh /usr/local/bin/kopano-cli
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-dbadm.sh /usr/local/bin/kopano-dbadm
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-fix-ipm-subtree.sh /usr/local/bin/kopano-fix-ipm-subtree
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-fsck.sh /usr/local/bin/kopano-fsck
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-localize-folders.sh /usr/local/bin/kopano-localize-folders
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-mailbox-permissions.sh /usr/local/bin/kopano-mailbox-permissions
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-migration-imap.sh /usr/local/bin/kopano-migration-imap
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-migration-pst.sh /usr/local/bin/kopano-migration-pst
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-passwd.sh /usr/local/bin/kopano-passwd
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-recreate-systemfolders.sh /usr/local/bin/kopano-recreate-systemfolders
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-set-oof.sh /usr/local/bin/kopano-set-oof
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-srvadm.sh /usr/local/bin/kopano-srvadm
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-storeadm.sh /usr/local/bin/kopano-storeadm
	ln -sf /var/packages/Kopano4s/scripts/wrapper/z-push-admin.sh /usr/local/bin/z-push-admin
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-devicelist.sh /usr/local/bin/kopano-devicelist
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-userlist.sh /usr/local/bin/kopano-userlist
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-folderlist.sh /usr/local/bin/kopano-folderlist
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-pubfolders.sh /usr/local/bin/kopano-pubfolders
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-postfix.sh /usr/local/bin/kopano-postfix
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-fetchmail.sh /usr/local/bin/kopano-fetchmail
	ln -sf /var/packages/Kopano4s/scripts/wrapper/sendmail.sh /usr/sbin/sendmail
	ln -sf /var/packages/Kopano4s/scripts/wrapper/sendmail.sh /usr/local/bin/mail
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-status.sh /usr/local/bin/kopano-status
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-restart.sh /usr/local/bin/kopano-restart
	ln -sf /var/packages/Kopano4s/scripts/addon/kopano4s-autoblock.sh /usr/local/bin/kopano4s-autoblock
	ln -sf /var/packages/Kopano4s/scripts/addon/kopano4s-backup.sh /usr/local/bin/kopano4s-backup
	ln -sf /var/packages/Kopano4s/scripts/addon/kopano4s-hubtag.sh /usr/local/bin/kopano4s-hubtag
	ln -sf /var/packages/Kopano4s/scripts/addon/kopano4s-init.sh /usr/local/bin/kopano4s-init
	ln -sf /var/packages/Kopano4s/scripts/addon/kopano4s-migration-zarafa.sh /usr/local/bin/kopano4s-migration-zarafa
	ln -sf /var/packages/Kopano4s/scripts/addon/kopano4s-optionals.sh /usr/local/bin/kopano4s-optionals
	ln -sf /var/packages/Kopano4s/scripts/addon/kopano4s-replication.sh /usr/local/bin/kopano4s-replication
	ln -sf /var/packages/Kopano4s/scripts/addon/kopano4s-restore-user.sh /usr/local/bin/kopano4s-restore-user
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-cmdline.sh /usr/local/bin/kopano-cmdline
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-cmdline.sh /usr/local/bin/kopano4s
	ln -sf /var/packages/Kopano4s/scripts/wrapper/kopano-cmdline.sh /usr/local/bin/k4s
	touch "$K_SHARE/backup/mySqlDump.log"
	ln -sf "$K_SHARE/backup/mySqlDump.log" "$TARGET_PATH/log/sqlbackup.log"
	ln -sf "$ETC_PATH/kopano" /etc/kopano
	ln -sf "$ETC_PATH/z-push" /etc/z-push
	ln -sf "$K_SHARE/run" /var/run/kopano
	ln -sf "$K_SHARE/log" /var/log/kopano
	ln -sf "$K_SHARE/log" "$TARGET_PATH/log/kopano"
	# cleanup container sub-dir in scripts dir
	if [ -e /var/packages/Kopano4s/scripts/container ] ; then rm -R /var/packages/Kopano4s/scripts/container ; fi
}
# ** build docker image
BUILD_DOCKER()
{
	local BUILD_PARAMS
	local TAG1
	local TAG2
	local TAG3
	local TAG4
	local IMG_TAG
	local DATE_BUILD
	DATE_BUILD=$(date "+%Y-%m-%d")
	NOTIFY_MESSAGE "Please ignore potential install errors during 12-35min docker build time: this is a Synology package installer time-out.."
	LOG_MESSAGE "Building Kopano4s in Docker container: 12-35 min see docker-kopano-build.log"
	if [ "$PKGWIZ_NO_GUI" = "true" ] ; then echo "Building Kopano4s in Docker container: 12-35 min see docker-kopano-build.log" ; fi
	mkdir -p "$DOCKER_PATH"/kopano4s
	mkdir -p "$DOCKER_PATH"/kopano4s/container
	# copy over dockerfile and cfg for packages to remove post build, then conatiner init, robot.png
	if [ -e /var/packages/Kopano4s/scripts/container ]
	then
		cp -f /var/packages/Kopano4s/scripts/container/Dockerfile "$DOCKER_PATH"/kopano4s
		cp -f /var/packages/Kopano4s/scripts/container/*.sh "$DOCKER_PATH"/kopano4s/container
		cp -f /var/packages/Kopano4s/scripts/container/dpkg-remove "$DOCKER_PATH"/kopano4s/container
		cp -f "$TARGET_PATH/merge/kopano-cfg.tgz" "$DOCKER_PATH"/kopano4s/container
		cp -f "$TARGET_PATH/merge/kinit.tgz" "$DOCKER_PATH"/kopano4s/container
		cp -f "$TARGET_PATH/ui/images/robot.png" "$DOCKER_PATH"/kopano4s/container
	fi
	echo "Calling kopano4s Dockerfile build at $(date "+%Y%m%d-%H:%M:%S").." >"$TARGET_PATH"/log/docker-kopano-build.log
	BUILD_PARAMS="--build-arg EDITION=${K_EDITION} --build-arg PHP_VER=$PHP_VER"
	# for supported and community edition get dynamic version tag
	if [ "$K_EDITION" = "Community" ]
	then
		TAG1=$( GET_K_DOWNLOAD_RELEASE_TAG "https://download.kopano.io/community/core:/" "Debian_9.0" )
		if [ -z "$TAG1" ]
		then
			echo "Could not evaluate Kopano core release tag from download; exiting.."
			exit 1
		fi
		TAG2=$( GET_K_DOWNLOAD_RELEASE_TAG "https://download.kopano.io/community/webapp:/" "Debian_9.0" )
		if [ -z "$TAG2" ]
		then
			echo "Could not evaluate Kopano webapp release tag from download; exiting.."
			exit 1
		fi
		TAG3=$( GET_K_DOWNLOAD_RELEASE_TAG "http://repo.z-hub.io/z-push:/final/Debian_9.0/all/" "z-push-kopano_" )
		if [ -z "$TAG3" ]
		then
			echo "Could not evaluate Kopano z-push release tag from download; exiting.."
			exit 1
		fi
		TAG4=$( GET_K_DOWNLOAD_RELEASE_TAG "https://download.kopano.io/community/webmeetings:/" "Debian_9.0" )
		if [ -z "$TAG4" ]
		then
			echo "Could not evaluate Kopano webmeetings release tag from download; exiting.."
			exit 1
		fi	
		IMG_TAG="Core-${TAG1}_Webapp-${TAG2}_Z-Push-${TAG3}_WMeet-${TAG4}"
		VER_TAG="C-${IMG_TAG}"
		BUILD_PARAMS="$BUILD_PARAMS --build-arg COMMUNITY_BUILD=1"
	fi
	if [ "$K_EDITION" = "Supported" ]
	then
		TAG1=$( GET_K_DOWNLOAD_RELEASE_TAG "https://serial:${K_SNR}@download.kopano.io/supported/core:/final/tarballs/" "Debian_9.0" )
		if [ -z "$TAG1" ]
		then
			echo "Could not evaluate Kopano core release tag from download; exiting.."
			exit 1
		fi
		TAG2=$( GET_K_DOWNLOAD_RELEASE_TAG "https://serial:${K_SNR}@download.kopano.io/supported/webapp:/final/tarballs/" "Debian_9.0" )
		if [ -z "$TAG2" ]
		then
			echo "Could not evaluate Kopano webapp release tag from download; exiting.."
			exit 1
		fi
		TAG3=$( GET_K_DOWNLOAD_RELEASE_TAG "http://repo.z-hub.io/z-push:/final/Debian_9.0/all/" "z-push-kopano_" )
		if [ -z "$TAG3" ]
		then
			echo "Could not evaluate Kopano z-push release tag from download; exiting.."
			exit 1
		fi
		TAG4=$( GET_K_DOWNLOAD_RELEASE_TAG "https://serial:${K_SNR}@download.kopano.io/supported/webmeetings:/final/tarballs/" "Debian_9.0" )
		if [ -z "$TAG4" ]
		then
			echo "Could not evaluate Kopano webmeetings release tag from download; exiting.."
			exit 1
		fi	
		IMG_TAG="Core-${TAG1}_Webapp-${TAG2}_Z-Push-${TAG3}_WMeet-${TAG4}"
		VER_TAG="S-${IMG_TAG}"
		# passing SNR for download via arg http_proxy not found in docker history.
		BUILD_PARAMS="$BUILD_PARAMS --build-arg SUPPORTED_BUILD=1 --build-arg K_SNR=${K_SNR}"
	fi
	if [ "$K_EDITION" = "Default" ]
	then
		IMG_TAG="$DEFAULT_TAG"
		VER_TAG="D-${IMG_TAG}"
		BUILD_PARAMS="$BUILD_PARAMS --build-arg DEFAULT_BUILD=1 --build-arg K_SNR=${K_SNR}"
	fi
	if [ "$K_EDITION" = "Migration" ]
	then
		IMG_TAG="$MIGRATION_TAG"
		VER_TAG="M-${IMG_TAG}"
		BUILD_PARAMS="$BUILD_PARAMS --build-arg MIGRATION_BUILD=1 --build-arg K_SNR=${K_SNR}"
	fi
	BUILD_PARAMS="$BUILD_PARAMS --build-arg PARENT=${DOCKER_HOST} --build-arg BUILD=${DATE_BUILD} --build-arg TAG=${IMG_TAG} --tag tosoboso/kopano4s:${VER_TAG}"
	sed -i -e "s~VER_TAG=.*~VER_TAG=\"$VER_TAG\"~" $ETC_PATH/package.cfg
	docker build "$DOCKER_PATH"/kopano4s "${BUILD_PARAMS}" >>"$TARGET_PATH/log/docker-kopano-build.log" 2>&1
	NOTIFY_MESSAGE "Building Kopano4s container $VER_TAG sucessfully completed"	
	if [ "$PKGWIZ_NO_GUI" = "true" ] ; then echo "Building Kopano4s container $VER_TAG sucessfully completed" ; fi
}
# ** drop section of unistall (SOFTLINKS / USER_DATBASE / MYSQL_TUNING) 
# ** drop all softlinks and nginx onfig for reverse proxy webapp
DROP_SOFTLINKS()
{
	# remove kopano etc and scripts linked into the box
	rm /usr/local/bin/kopano*
	rm /usr/local/bin/k4s
	rm /usr/sbin/sendmail
	rm /usr/local/bin/mail
	rm /usr/local/bin/z-push*
	rm /etc/kopano
	rm /var/run/kopano
	if [ -e /usr/local/etc/nginx/conf.d/www.Kopano4s.conf ] ; then rm /usr/local/etc/nginx/conf.d/www.Kopano4s.conf ; fi
}
# ** drop user and database unless kepp was selected in WIZZARD-UI
DROP_USER_DATABASE()
{
	if [ "$PKGWIZ_NO_GUI" = "true" ] ; then echo "deleting kopano database in cmd-line mode you have to pass the mysql root pwd.." ; fi
	local DB_MPASS="$PKGWIZ_DB_PASSWD"
	local SQL_DROP_USR="DROP USER '$DB_USER'@'localhost';"
	local SQL_DROP_DB="DROP DATABASE \`$DB_NAME\`;"
	$MYSQL -uroot -p"${DB_MPASS}" -e "$SQL_DROP_USR" >/tmp/out.sql 2>&1
	local ERR=$?
	local RET
	if [ "$ERR" -eq 1 ]
	then
		RET=$(cat /tmp/out.sql)
		# for our wow no pwd candidates
		$MYSQL -uroot -p -e "$SQL_DROP_USR"
		if [ "$ERR" -gt 0 ]
		then
			echo "Error in SQL: $RET"
			LOG_MESSAGE "Error deleting user: $RET"
			if [ "$PKGWIZ_NO_GUI" = "true" ] ; then echo "Error deleting user: $RET" ; fi
			exit 1
		fi
	fi
	if [ "$PKGWIZ_KEEP_DB" == "false" ]
	then
		$MYSQL -uroot -p"${DB_MPASS}" -e "$SQL_DROP_DB" >/tmp/out.sql 2>&1
		ERR=$?
		if [ "$ERR" -eq 1 ]
		then
			RET=$(cat /tmp/out.sql)
			echo "Error in SQL: $RET"
			GUI_MESSAGE "Error deleting database: $RET"
			exit 1
		fi
	fi
	if [ "$PKGWIZ_KEEP_SHARE" == "false" ]
	then
		synoshare --del TRUE kopano
	fi
	if [ "$PKGWIZ_KEEP_USER" == "false" ]
	then
		synouser --del kopano
		synogroup --del kopano
		synouser --del k4samavis
	fi
}
DROP_DOCKER()
{
	# always remove the kopano4s docker container and optionally the image
	if docker ps -a | grep -q kopano4s
	then
		docker stop kopano4s && docker rm kopano4s
	fi
	if [ "$PKGWIZ_KEEP_K4S_IMAGE" = "false" ]
	then
		if docker images | grep -q tosoboso/kopano4s
		then
			docker rmi tosoboso/kopano4s:"$VER_TAG"
		fi
	fi
	if [ "$PKGWIZ_KEEP_BASE_IMAGE" = "false" ]
	then
		if docker images | grep -q stretch-slim
		then
			docker rmi debian:stretch-slim
		fi
	fi
	if [ -e "$DOCKER_PATH/kopano4s" ] ; then rm -R "$DOCKER_PATH/kopano4s" ; fi
}
# at upgrade drop old docker image and container
DROP_OLD_DOCKER()
{
	if docker ps -a | grep -q kopano4s
	then
		docker stop kopano4s && docker rm kopano4s
	fi
	if docker images | grep -q tosoboso/kopano4s
	then
		docker rmi tosoboso/kopano4s:"$OLD_VER_TAG"
	fi
}
DROP_MYSQL_TUNING()
{
	if [ "$TUNING_BUFFER" -gt 0 ]
	then
		REMOVE="innodb_buffer_pool_size = ${INNODB_BUFFER}M"
		sed -i -e "s~$REMOVE~~" /var/packages/MariaDB10/etc/my.cnf
		sed -i -e "s~#kopano4s overwrite default innodb_buffer as 16M~~" /var/packages/MariaDB10/etc/my.cnf
	fi
}
