#!/bin/sh
# ** (c) 2018 vbettag - install for Kopano4Syno in Docker container
# ** get library and common procedures, settings, tags and download urls
MYDIR=$(dirname "$0")
. "$MYDIR"/library
. "$MYDIR"/common
if [ "$RELEASE" = "Beta" ] ; then echo "$(date '+%Y.%m.%d-%H:%M:%S') postinst start" >> /tmp/k4sinst.log ; fi
if [ "$SYNOPKG_PKG_STATUS" != "UPGRADE" ]
# ** install only modus
then
	# ** get config from package wizzard tags, stale vs. beta from INFO and calculate tuning
	GET_BETA_STABLE
	# GET_WIZZARD_CFG includes GET_WIZZARD_EDITION & GET_WIZZARD_SIZE
	GET_WIZZARD_CFG
	if [ "$PKGWIZ_TUNING_BUFFER_0" = "true" ]
	then
		TUNING_BUFFER=0
		INNODB_BUFFER=16
		SYNO_MEMG=0
	else
		GET_TUNIG_PARAMS
	fi
	# ** inits: create log, user, group, share, mounts, etc, database
	INIT_LOG
	INIT_USR_GRP
	INIT_SHARE_ETC
	INIT_DATABASE
	# ** set config options as per install wizzard GUI
	SET_CFG_OPTIONS
	SET_OPTIONALS
	# ** set ssl, locales, sql and tune mariadb sql server 
	SET_K_CERTIFICATE
	SET_K_LOCALE
	SET_SQL_CONF
	GET_VER_TAG
	# ** set state and write cfg
	INSTALL_STATE="installing"
	SET_PKG_CFG
# ** upgrade only modus
else
	# ** in upgrade mode.. if previous steps failed create dummy config
	if [ ! -e "$ETC_PATH/package.cfg" ] ; then touch "$ETC_PATH"/package.cfg ; fi
	GET_PKG_CFG
	RESTORE_LOG_ETC
	if [ -z "$INSTALL_STATE" ] || [ "$INSTALL_STATE" != "completed" ]
	then
		LOG_MESSAGE "Cannot upgrade a previously uncompleted or legacy install. Please remove the package and re-install. "
		GUI_MESSAGE "Cannot upgrade a previously uncompleted or legacy install. Please remove the package and re-install. "
		exit 1
	fi
	# ensure all users exist
	INIT_USR_GRP
	INIT_UPDATE
	# any upgrade set beta vs. stable
	GET_BETA_STABLE
	GET_VER_TAG
	# ** save package config again for changed tags and state
	INSTALL_STATE="upgrading"
	SET_PKG_CFG
	# default no image build at upgrade
	IMAGE_BUILD="OFF"
fi
if [ "$RELEASE" = "Beta" ] ; then echo "postinst edition:${K_EDITION}, tag:${VER_TAG}, mode:${SYNOPKG_PKG_STATUS}" >> /tmp/k4sinst.log ; fi
# ** install & upgrade modus
INIT_SYNOACL
# we do not find the latest or predefined tag so we have to build
if ! CHECK_DOCKER_TAG tosoboso/kopano4s "$VER_TAG"
then
	IMAGE_BUILD="ON"
fi
if [ "$IMAGE_BUILD" = "ON" ]
then
	if [ "$RELEASE" = "Beta" ] ; then echo "$(date '+%Y.%m.%d-%H:%M:%S') postinst build docker" >> /tmp/k4sinst.log ; fi
	STARTTIME=$(date +%s)
	BUILD_DOCKER
fi
SET_GUI_NO_DEBUG
SET_COMMUNITY_BETA
SET_SVR_CFG_NEW
SET_SOFTLINKS
# change install state to completed
sed -i -e 's~INSTALL_STATE=.*~INSTALL_STATE="completed"~' "$ETC_PATH"/package.cfg
if [ "$SYNOPKG_PKG_STATUS" != "UPGRADE" ]
then
	MSG="Kopano4s install of $VER_TAG completed sucessfully."
else
	MSG="Kopano4s upgrade to $VER_TAG completed sucessfully."
fi
LOG_MESSAGE "$MSG"
NOTIFY_MESSAGE "$MSG"
if [ "$RELEASE" = "Beta" ] ; then echo "$(date '+%Y.%m.%d-%H:%M:%S') postinst done" >> /tmp/k4sinst.log ; fi
exit 0
