#!/bin/sh
# ** (c) 2018 vbettag - install for Kopano4s in Docker container
#echo "$(date '+%Y.%m.%d-%H:%M:%S') postuninst" >> /tmp/inst.log
# ** get common procedures, settings, tags and download urls
MYDIR=$(dirname "$0")
. "$MYDIR"/common
GET_PKG_CFG
# postuninst is also called during upgrade procedures which we deal with seperately
if [ "$SYNOPKG_PKG_STATUS" != UPGRADE ]
then
	DROP_SOFTLINKS
	DROP_USER_DATABASE
	DROP_DOCKER
	DROP_MYSQL_TUNING
	# now delete the etc area to avoid it left orphaned
	rm -R /usr/syno/etc/packages/Kopano4s
fi
#echo "$(date '+%Y.%m.%d-%H:%M:%S') postuninst done" >> /tmp/inst.log
exit 0
