#!/bin/sh
# ** (c) 2018 vbettag - install for Kopano4s in Docker container
# ** get library and common procedures, settings, tags and download urls
MYDIR=$(dirname "$0")
. "$MYDIR"/library
. "$MYDIR"/common
if [ "$RELEASE" = "Beta" ] ; then echo "$(date '+%Y.%m.%d-%H:%M:%S') postuninst start" >> /tmp/k4sinst.log ; fi
GET_PKG_CFG
# postuninst is also called during upgrade procedures which we deal with seperately
if [ "$SYNOPKG_PKG_STATUS" != UPGRADE ]
then
	if [ "$RELEASE" = "Beta" ] ; then echo "$(date '+%Y.%m.%d-%H:%M:%S') postuninst $SYNOPKG_PKG_STATUS drop tasks" >> /tmp/k4sinst.log ; fi
	DROP_SOFTLINKS
	DROP_USER_DATABASE_SHARE
	DROP_DOCKER
	DROP_MYSQL_TUNING
	# now delete the etc area to avoid it left orphaned
	rm -R /usr/syno/etc/packages/Kopano4s
fi
if [ "$RELEASE" = "Beta" ] ; then echo "$(date '+%Y.%m.%d-%H:%M:%S') postuninst done" >> /tmp/k4sinst.log ; fi
exit 0
