#!/bin/sh
# ** get common procedures, settings, tags and download urls
#echo "$(date '+%Y.%m.%d-%H:%M:%S') preupgrade" >> /tmp/inst.log
MYDIR=$(dirname "$0")
. "$MYDIR"/common
if [ ! -e "$ETC_PATH"/package.cfg ] ; then touch "$ETC_PATH"/package.cfg ; fi
GET_PKG_CFG
if [ -z "$INSTALL_STATE" ] || [ "$INSTALL_STATE" != "completed" ]
then
	GUI_MESSAGE "No upgrade to previously uncompleted or legacy install. Please remove and install again. "
	exit 1
fi
if [ "$RELEASE" = "Stable" ] && [ "$K_EDITION" = "Community" ]
then
	GUI_MESSAGE "No upgrade from beta community version to default or supported please run kopano-backup then remove database and install again followed by kopano4s-resoter-users all. "
	exit 1
fi

# ** backup install-log & etc
SAVE_LOG_ETC
OLD_VER_TAG="$VER_TAG"
GET_VER_TAG
if [ "$OLD_VER_TAG" != "$VER_TAG" ]
then
	DROP_OLD_DOCKER
	echo "$(date '+%Y.%m.%d-%H:%M:%S') preupgrade: drop docker $OLD_VER_TAG" >> /tmp/inst.log
fi
#echo "$(date '+%Y.%m.%d-%H:%M:%S') preupgrade done" >> /tmp/inst.log
exit 0

