#!/bin/sh
# ** get library and common procedures, settings, tags and download urls
MYDIR=$(dirname "$0")
. "$MYDIR"/library
. "$MYDIR"/common
if [ "$RELEASE" = "Beta" ] && [ -e /tmp/k4sinst.log ] && [ "$SYNOPKG_PKG_STATUS" = "UPGRADE" ] ; then rm /tmp/k4sinst.log ; fi
if [ "$RELEASE" = "Beta" ] ; then echo "$(date '+%Y.%m.%d-%H:%M:%S') preupgrade start" >> /tmp/k4sinst.log ; fi
if [ ! -e "$ETC_PATH"/package.cfg ] ; then touch "$ETC_PATH"/package.cfg ; fi

GET_PKG_CFG
if [ "$RELEASE" = "Beta" ] ; then echo "$(date '+%Y.%m.%d-%H:%M:%S') preupgrade state:${INSTALL_STATE}, edition:${K_EDITION}, tag:${VER_TAG}, mode:${SYNOPKG_PKG_STATUS}" >> /tmp/k4sinst.log ; fi
if [ -z "$INSTALL_STATE" ] || [ "$INSTALL_STATE" != "completed" ]
then
	GUI_MESSAGE "No upgrade to previously uncompleted or legacy install. Please remove and install again."
	exit 1
fi
if [ "$RELEASE" = "Stable" ] && [ "$K_EDITION" = "Community" ]
then
	GUI_MESSAGE "No upgrade from beta community version to default or supported please run kopano-backup then remove database and install again followed by kopano4s-restore-user all or kopano4s-downgrade which combines the tasks. "
	exit 1
fi

# ** backup install-log & etc
SAVE_LOG_ETC
OLD_VER_TAG="$VER_TAG"
GET_VER_TAG
if [ "$OLD_VER_TAG" != "$VER_TAG" ]
then
	DROP_OLD_DOCKER
	if [ "$RELEASE" = "Beta" ] ; then echo "$(date '+%Y.%m.%d-%H:%M:%S') preupgrade: drop $OLD_VER_TAG" >> /tmp/k4sinst.log ; fi
fi
if [ "$RELEASE" = "Beta" ] ; then echo "$(date '+%Y.%m.%d-%H:%M:%S') preupgrade done" >> /tmp/k4sinst.log ; fi
exit 0

