# now the main container in which we copy the local repo from interim container
FROM debian:stretch-slim
MAINTAINER vbettag "tosoboso@web.de"
# set arg and env variables respectively urls and DEBIAN_FRONTEND to noninteractive
ENV BUILD="2018-12-26" \
	EDITION="Kopano-Edition" \
	TAG="Build-Tag" \
	PARENT=${NO_PROXY} \
	LANG="en_GB.UTF-8" \
	LANGUAGE="en_GB.UTF-8" \
	LC_ALL="en_GB.UTF-8" \
	PHP_VER="7.0" \
	TERM=ansi \
	DEBIAN_FRONTEND=noninteractive
WORKDIR /root
COPY /container/dpkg-remove /root/dpkg-remove
COPY /container/*.png /root/
COPY /container/*.sh /usr/local/bin/
# TB Docker tuning: will be disabled in 2nd as 2 step build pproach to save ~50MB space in container
#COPY --from=k4s-intermediate /root/kopano-repo.tgz /root/kopano-repo.tgz
RUN PASSWD="openssl rand -base64 32"
# layer 2 step 16 or 17: merging run layers to save space in nested docker file syatem
RUN echo "** setup debian system basics incl. nginx, php-${PHP_VER} then postfix, fetchmail, amavisd, spamassassin, clamav, postgrey...." && \ 
	apt-get update -y > /etc/update.list && apt-get install -y --no-install-recommends --assume-yes \ 
	wget locales apt-transport-https ssl-cert ca-certificates rsyslog dialog nginx-light && \
	# remove nginx files and prepare for php7.x-fpm instead of php-fpm which is 7.0 EOL
	rm /etc/nginx/sites-enabled/default && rm /var/www/html/index.nginx-debian.html && \
	wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg && \
	if [ "$PHP_VER" != "7.0" ] ; then echo "deb https://packages.sury.org/php/ stretch main" > /etc/apt/sources.list.d/php.list ; fi && \
	apt-get update -y > /etc/update.list && apt-get install -y --no-install-recommends php${PHP_VER}-fpm && \
	# set locales GB/US UTF-8 and DE plus CET timezone plus optional other locale at build time
	sed -i -e "s~# en_GB.UTF-8~en_GB.UTF-8~" /etc/locale.gen && sed -i -e "s~# en_US.UTF-8~en_US.UTF-8~" /etc/locale.gen && \
	sed -i -e "s~# de_DE.UTF-8~de_DE.UTF-8~" /etc/locale.gen && \
	if [ ! -e /usr/share/locale/locale.alias ] ; then ln -s /etc/locale.alias /usr/share/locale/locale.alias ; fi && \
	ln -sf /usr/share/zoneinfo/CET /etc/localtime && dpkg-reconfigure locales && dpkg-reconfigure tzdata && \
	if echo $EDITION | grep -q "Supported" ; then touch /etc/K_SUPPORTED ; else touch /etc/K_COMMUNITY ; fi && \
	groupmod -g 1023 www-data && usermod -u 1023 -g 1023 www-data && mkdir -p /var/lib/postgrey/ && \ 
	apt-get install -y --allow-unauthenticated --no-install-recommends --assume-yes \
	postfix pflogsumm libsasl2-modules fetchmail amavisd-new spamassassin postgrey clamav-daemon clamav-freshclam \
	# more perl and zip libraries for scanning
	libnet-dns-perl libmail-spf-perl pyzor razor arj bzip2 cabextract cpio file gzip nomarch pax unzip zoo zip zoo && rm -rf /var/lib/apt/lists/* && \
# TB Docker tuning: 2 step approach to shrink the Docker image: 1st run collect kopano-repo.tgz in kopano-etc for outside of container
#	mkdir /etc/kopano && cp /root/kopano-repo.tgz /etc/kopano && \ 
# TB Docker tuning: 2nd step provide kopano-repo.tgz via internal webserver in protected tools url and disable COPY --from=k4s-intermediate
	wget $PARENT/tools/kopano-repo.tgz && \ 
# layer 2 step 8 or 9 prepare, download and install kopano
	echo "** setup kopano: user, downoad, install core, licensed, webmeetings incl. add-ons, z-push incl. autodiscover...." && \
	groupadd -g 65540 kopano && useradd -u 1030 -g 65540 -p$PASSWD -M kopano && \
	usermod -d/usr/share/kopano kopano -s/bin/false -c'kopano demon with Synology UID' && usermod -Gkopano -a root && \
	# change usr-grp-ids and add scanner users to respective groups to allow file handling for amavis under kopano
	groupmod -g 130 amavis && usermod -u 130 -g 130 amavis && groupmod -g 129 clamav && usermod -u 129 -g 129 clamav && \
	groupmod -g 128 debian-spamd && usermod -u 128 -g 128 debian-spamd && groupmod -g 127 postgrey && usermod -u 127 -g 127 postgrey && \
	usermod -u 126 fetchmail && groupmod -g 125 postfix && usermod -u 125 -g 125 postfix && \
	adduser clamav amavis && adduser amavis clamav && adduser amavis debian-spamd && adduser debian-spamd amavis && \
	adduser clamav kopano && adduser amavis kopano && adduser debian-spamd kopano && \ 
# create z-push directories for etc and state plus and set the ownership
	mkdir -p /var/log/kopano && mkdir -p /var/log/kopano/z-push && ln -sf /var/log/kopano/z-push /var/log/z-push && \
	mkdir -p /etc/kopano && mkdir -p /etc/kopano/web && mkdir -p /etc/z-push  && mkdir -p /var/lib/z-push && \
	chown -R www-data.kopano /var/log/kopano/z-push && chown -R www-data.kopano /etc/z-push && chown -R www-data.www-data /var/lib/z-push && \
# install kopano, z-push, webapp and plugins using pepo from interim build incl. kopano.mo locales for localized mail-folders
	chmod 711 /root && echo "deb [trusted=yes] file:/root/repo kopano main" > /etc/apt/sources.list.d/kopano.list && \
	tar -zxvf /root/kopano-repo.tgz -C /root && rm /root/kopano-repo.tgz && \
# copy config and init.d files as on latest versions they are missing (KC-681); duak-cfg triggers error so only for supported
#KC-681	cp /root/repo/kinit.d/* /etc/init.d/ && mkdir -p /etc/kopano && cp /root/repo/kopano.cfg/* /etc/kopano && \
# presence and webmeetings still have cfg and init shiped so delete them
#KC-681	if [ -e /etc/init.d/kopano-presence ] ; then rm /etc/init.d/kopano-presence ; fi && \
#KC-681	if [ -e /etc/kopano/presence.cfg ] ; then rm /etc/kopano/presence.cfg ; fi && \
#KC-681	if [ -e /etc/init.d/kopano-webmeetings ] ; then rm /etc/init.d/kopano-webmeetings ; fi && \
#KC-681	if [ -e /etc/kopano/webmeetings.cfg ] ; then rm /etc/kopano/webmeetings.cfg ; fi && \
	if [ -e /root/repo/locale/de ] ; then cp -R /root/repo/locale/* /usr/share/locale ; fi && \
	apt-get update -y > /etc/update.list && apt-get install --no-install-recommends --allow-unauthenticated --assume-yes \ 
	kopano-server-packages kopano-migration-imap kopano-migration-pst kopano-spamd \
	z-push-kopano z-push-kopano-gabsync z-push-kopano-gab2contacts z-push-autodiscover \
#FULL	kopano-presence \
#FULL	kopano-webmeetings \
	kopano-webapp \
#FULL	kopano-webapp-plugin-meetings \
	kopano-webapp-plugin-contactfax \
	kopano-webapp-plugin-desktopnotifications \
	kopano-webapp-plugin-filepreviewer \
#FULL	kopano-webapp-plugin-files kopano-webapp-plugin-filesbackend-smb kopano-webapp-plugin-filesbackend-owncloud \
	kopano-webapp-plugin-folderwidgets \
	kopano-webapp-plugin-gmaps \
	kopano-webapp-plugin-intranet \
#FULL	kopano-webapp-plugin-mattermost \
	kopano-webapp-plugin-mdm \
	kopano-webapp-plugin-pimfolder \
	kopano-webapp-plugin-quickitems \
	kopano-webapp-plugin-smime \
	kopano-webapp-plugin-spell-en \
	kopano-webapp-plugin-spell-de-de \
	kopano-webapp-plugin-spell-es \
	kopano-webapp-plugin-spell-fr \
	kopano-webapp-plugin-spell-it \
	kopano-webapp-plugin-spell-nl \
	kopano-webapp-plugin-titlecounter \
	kopano-webapp-plugin-webappmanual && \
# copy over non core kopano plugins
	if [ -e /root/repo/plugins ] ; then cp -R /root/repo/plugins /usr/share/kopano-webapp ; fi && \
	apt-get upgrade --no-install-recommends --allow-unauthenticated --assume-yes && \
#FULL	if [ ! -e /etc/init.d/kopano-presence ] ; then cp /root/repo/kinit.d/kopano-presence /etc/init.d/kopano-presence ; fi && \
	rm -rf /var/lib/apt/lists/* /root/repo && \
# layer 3 cleanup: remove obsolete packages and config, autoremove, move and softlink stuff
	#if [ "$PHP_VER" != "7.0" ] ; then dpkg-query -Wf '${Package}\n' | grep php7.0 >> dpkg-remove ; fi && \
	apt-get remove -y --assume-yes $(grep -vE "^\s*#" dpkg-remove | tr "\n" " ") && \
	apt-get autoremove -y  && \
	dpkg --list | grep "^rc" | cut -d " " -f 3 | xargs --no-run-if-empty dpkg --purge  && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /etc/apt/sources.list.d/kopano.list /root/dpkg-remove && chmod 755 /etc/init.d/kopano-* && \
# add touch, chmod PIDFILE to kopano service init files and change stop on name instead of exec, special case: search, spamd with pyton
	K_SRVS=`ls /etc/init.d/kopano-*` && for S in $K_SRVS; do sed -i -e "s~start-stop-daemon --start \$QUIETDAEMON~touch \$PIDFILE \&\& chown kopano.kopano \$PIDFILE \n\tstart-stop-daemon --start \$QUIETDAEMON~" $S  && \
	sed -i -e "s~start-stop-daemon --stop \$QUIETDAEMON.*~start-stop-daemon --stop \$QUIETDAEMON --pidfile \$PIDFILE --name \$NAME --retry TERM/15/KILL >/dev/null~g" $S ; done  && \
	sed -i -e "s~search.pid~searchm.pid~" /etc/init.d/kopano-search && sed -i -e "s~--name \$NAME ~~g" /etc/init.d/kopano-search && \
	sed -i -e "s~unset LC_ALL~PID=\`ps -ef | grep /usr/sbin/kopano-search | head -1 | awk '{print \$2}'\` \&\& echo \$PID > \$PIDFILE\n\tunset LC_ALL~" /etc/init.d/kopano-search && \
	sed -i -e "s~/usr/bin/python ~~" /etc/init.d/kopano-search && \
#KC-681	sed -i -e "s~spamd.pid~spamdm.pid~" /etc/init.d/kopano-spamd && sed -i -e "s~--name \$NAME ~~g" /etc/init.d/kopano-spamd && \
#KC-681	sed -i -e "s~unset LC_ALL LANG~PID=\`ps -ef | grep /usr/sbin/kopano-spamd | head -1 | awk '{print \$2}'\` \&\& echo \$PID > \$PIDFILE\n\tunset LC_ALL LANG~" /etc/init.d/kopano-spamd && \
#KC-681	sed -i -e "s~/usr/bin/python ~~" /etc/init.d/kopano-spamd && \
#FULL	sed -i -e "s~presence.pid~presencem.pid~" /etc/init.d/kopano-presence && sed -i -e "s~--name \$NAME ~~g" /etc/init.d/kopano-presence && \
#FULL	sed -i -e "s~unset LC_ALL~PID=\`ps -ef | grep /usr/sbin/kopano-presence | head -1 | awk '{print \$2}'\` \&\& echo \$PID > \$PIDFILE\n\tunset LC_ALL~" /etc/init.d/kopano-presence && \
# exclude userscripts from exposed mountpoint in synology softlink it instead,
	mv /etc/kopano/userscripts /etc/kopano/k-userscripts && \
	cp -R /etc/kopano/k-userscripts /etc && rm -R /etc/kopano/k-userscripts && \
	ln -sf /etc/k-userscripts /etc/kopano/userscripts && \
# robot for got lost, softlink webapp and z-push fron /usr area into html area so no alias is needed
	mv /root/robot.png /var/www/html && ln -sf /usr/share/kopano-webapp /var/www/html/webapp && ln -sf /usr/share/z-push /var/www/html/z-push && \
# more softlink stuff copying over etc and etc-default files
	if [ ! -e /etc/kopano/default ] && [ -e /etc/default/kopano ] ; then cp /etc/default/kopano /etc/kopano/default ; fi && \
	ln -sf /etc/kopano/default /etc/default/kopano && \
	if [ ! -e /etc/kopano/default-webmeetings ] && [ -e /etc/default/kopano-webmeetings ] ; then cp /etc/default/kopano-webmeetings /etc/kopano/default-webmeetings && ln -sf /etc/kopano/default-webmeetings /etc/default/kopano-webmeetings ; fi && \
	if [ ! -e /etc/kopano/default-postgrey ] && [ -e /etc/default/postgrey ] ; then cp /etc/default/postgrey /etc/kopano/default-postgrey ; fi && \
	ln -sf /etc/kopano/default-postgrey /etc/default/postgrey && \
	if [ ! -e /etc/kopano/default-spamassassin ] && [ -e /etc/default/spamassassin ] ; then cp /etc/default/spamassassin /etc/kopano/default-spamassassin ; fi && \
	ln -sf /etc/kopano/default-spamassassin /etc/default/spamassassin && \
	if [ ! -e /etc/kopano/default-amavis-mc ] && [ -e /etc/default/amavis-mc ] ; then cp /etc/default/amavis-mc /etc/kopano/default-amavis-mc ; fi && \
	ln -sf /etc/kopano/default-amavis-mc /etc/default/amavis-mc && \
	if [ ! -e /etc/kopano/default-amavisd-snmp-subagent ] && [ -e /etc/default/amavisd-snmp-subagent ] ; then cp /etc/default/amavisd-snmp-subagent /etc/kopano/default-amavisd-snmp-subagent ; fi && \
	ln -sf /etc/kopano/default-amavisd-snmp-subagent /etc/default/amavisd-snmp-subagent && \
	if [ ! -e /etc/kopano/default-amavis ] && [ -e /etc/amavis/conf.d/20-debian_defaults ] ; then cp /etc/amavis/conf.d/20-debian_defaults /etc/kopano/default-amavis ; fi && \
	ln -sf /etc/kopano/default-amavis /etc/amavis/conf.d/20-debian_defaults && \
	if [ ! -e /etc/kopano/user-amavis ] && [ -e /etc/amavis/conf.d/50-user ] ; then cp /etc/amavis/conf.d/50-user /etc/kopano/user-amavis ; fi && \
	ln -sf /etc/kopano/user-amavis /etc/amavis/conf.d/50-user && \
	if [ ! -e /etc/kopano/content_filter_mode ] && [ -e /etc/amavis/conf.d/15-content_filter_mode ] ; then cp /etc/amavis/conf.d/15-content_filter_mode /etc/kopano/content_filter_mode ; fi && \
	ln -sf /etc/kopano/content_filter_mode /etc/amavis/conf.d/15-content_filter_mode && \
	if [ ! -e /etc/kopano/default-fetchmail ] && [ -e /etc/default/fetchmail ] ; then cp /etc/default/fetchmail /etc/kopano/default-fetchmail ; fi && \
	ln -sf /etc/kopano/default-fetchmail /etc/default/fetchmail && \
	ln -sf /etc/kopano/fetchmailrc /etc/fetchmailrc && \
	ln -sf /etc/kopano/postfix/main.cf /etc/postfix/main.cf && \
	ln -sf /etc/kopano/postfix/master.cf /etc/postfix/master.cf && \
# create and softlink kopanos cron.daily and weekly 
	mkdir -p /etc/kopano/custom && echo '#!/bin/sh' > /etc/kopano/custom/cron.hourly && echo "# put your kopnao cron jobs here" >> /etc/kopano/custom/cron.hourly && \	
	cp /etc/kopano/custom/cron.hourly /etc/kopano/custom/cron.daily && cp /etc/kopano/custom/cron.daily /etc/kopano/custom/cron.weekly && chmod 750 /etc/kopano/custom/cron.* && chown root.kopano /etc/kopano/custom/cron.* && \
	ln -sf /etc/kopano/custom/cron.hourly /etc/cron.hourly/kopano && ln -sf /etc/kopano/custom/cron.daily /etc/cron.daily/kopano && ln -sf /etc/kopano/custom/cron.weekly /etc/cron.weekly/kopano && \
# prevent syslog logrotate warnings
	sed -i -e 's/\(printerror "could not determine current runlevel"\)/#\1/' /usr/sbin/invoke-rc.d && \
	sed -i -e 's/^\(POLICYHELPER=\).*/\1/' /usr/sbin/invoke-rc.d && \
# create logrotate in /etc/logrotate.d/ for amavis, daemon, fetchmail, messages, mail.*, php7*, spamassassin
	echo "/var/log/kopano/amavis.log {" > /etc/logrotate.d/amavis && \
	echo "su amavis kopano\nweekly\nmissingok\nrotate 4\ncompress\ndelaycompress\n}" >> /etc/logrotate.d/amavis && \
	echo "/var/log/kopano/daemon.log {" > /etc/logrotate.d/daemon && \
	echo "su root kopano\nweekly\nmissingok\nrotate 4\ncompress\ndelaycompress\n}" >> /etc/logrotate.d/daemon && \
	echo "/var/log/kopano/fetchmail.log {" > /etc/logrotate.d/fetchmail && \
	echo "su root kopano\nweekly\nmissingok\nrotate 4\ncompress\ndelaycompress\n}" >> /etc/logrotate.d/fetchmail && \
	echo "/var/log/kopano/messages.log {" > /etc/logrotate.d/messages && \
	echo "su root kopano\nweekly\nmissingok\nrotate 4\ncompress\ndelaycompress\n}" >> /etc/logrotate.d/messages && \
	echo "/var/log/kopano/mail.* {" > /etc/logrotate.d/mail && \
	echo "su root kopano\nweekly\nmissingok\nrotate 4\ncompress\ndelaycompress\n}" >> /etc/logrotate.d/mail && \
	echo "/var/log/kopano/php7*.log {" > /etc/logrotate.d/php7 && \
	echo "su root kopano\nweekly\nmissingok\nrotate 4\ncompress\ndelaycompress\n}" >> /etc/logrotate.d/php7 && \
	echo "/var/log/kopano/spamassassin.log {" > /etc/logrotate.d/spamassassin && \
	echo "su root kopano\nweekly\nmissingok\nrotate 4\ncompress\ndelaycompress\n}" >> /etc/logrotate.d/spamassassin && \
# now we set the logrotate path and permission via su user group in existing files in /etc/logrotate.d/
	sed -i -e "s~log {~log {\n\tsu kopano kopano~g"  /etc/logrotate.d/kopano && \
	sed -i -e "s~/var/log/~/var/log/kopano/~"  /etc/logrotate.d/z-push.lr && \
	sed -i -e "s~log {~log {\n\tsu www-data kopano~"  /etc/logrotate.d/z-push.lr && \
	sed -i -e "s~www-data www-data~www-data kopano~g"  /etc/logrotate.d/z-push.lr && \
	sed -i -e "s~log {~log {\n\tsu root kopano~"  /etc/logrotate.d/fetchmail && \
	sed -i -e "s~log {~log {\n\tsu root kopano~"  /etc/logrotate.d/clamav-daemon && \
	sed -i -e "s~log {~log {\n\tsu root kopano~"  /etc/logrotate.d/clamav-freshclam && \
	sed -i -e "s~/var/log/nginx/~/var/log/kopano/nginx~"  /etc/logrotate.d/nginx && \
	sed -i -e "s~log {~log {\n\tsu root kopano~"  /etc/logrotate.d/nginx && \
	sed -i -e "s~www-data adm~root kopano~"  /etc/logrotate.d/nginx && \
	sed -i -e "s~/var/log/syslog~/var/log/kopano/syslog~"  /etc/logrotate.d/rsyslog && \
	sed -i -e "s~{~{\n\tsu root kopano~"  /etc/logrotate.d/rsyslog && \
# expose postfix, nginx and other log files to kopano folder
	ln -sf /var/log/kopano/mail.log /var/log/mail.log && ln -sf /var/log/kopano/mail.info /var/log/mail.info  && \
	ln -sf /var/log/kopano/mail.warn /var/log/mail.warn && ln -sf /var/log/kopano/mail.err /var/log/mail.err && \
	if [ -e /var/log/clamav ] ; then rm -R /var/log/clamav ; fi  && ln -sf /var/log/kopano /var/log/clamav && \
	ln -sf /var/log/kopano/messages /var/log/messages && ln -sf /var/log/kopano/syslog /var/log/syslog && \
	ln -sf /var/log/kopano/daemon.log /var/log/daemon.log && ln -sf /var/log/kopano /var/log/spamassassin && \
	ln -sf /var/log/kopano/php${PHP_VER}-fpm.log /var/log/php${PHP_VER}-fpm.log && \
	ln -sf /var/log/kopano/nginx-access.log /var/log/nginx/access.log && ln -sf /var/log/kopano/nginx-error.log /var/log/nginx/error.log && \
# copy and softlink for webapp and all plugins by plugin-dir/config.php to /etc/kopano/webapp/config-pluginname.php
	if [ -e /usr/share/kopano-webapp/config.php ] && [ ! -e /etc/kopano/webapp/webapp.conf.php ] ; then cp /usr/share/kopano-webapp/config.php /etc/kopano/webapp/webapp.conf.php ; fi && \
	if [ -e /etc/kopano/webapp/webapp.conf.php ] ; then ln -sf /etc/kopano/webapp/webapp.conf.php /usr/share/kopano-webapp/config.php ; fi && \
	PDIR=`find /usr/share/kopano-webapp/plugins/* -maxdepth 0 -type d -exec basename "{}" ";"` && for P in $PDIR ; do if [ -e /usr/share/kopano-webapp/plugins/$P/config.php ] && [ ! -e /etc/kopano/webapp/plg.conf-${P}.php ] ; then cp /usr/share/kopano-webapp/plugins/$P/config.php /etc/kopano/webapp/plg.conf-${P}.php ; fi ; done && \ 
	for P in $PDIR ; do if [ -e /etc/kopano/webapp/plg.conf-${P}.php ] ; then ln -sf /etc/kopano/webapp/plg.conf-${P}.php /usr/share/kopano-webapp/plugins/$P/config.php ; fi ; done && \
# copy and softlink files for web server note php.ini gets overwritten and softlink re-estabilsiched via init
	cp /etc/php/$PHP_VER/fpm/php.ini /etc/kopano/web && \
	ln -sf /etc/kopano/web/php.ini /etc/php/$PHP_VER/fpm && \
	if [ -e /etc/php/$PHP_VER/mods-available/kopano.ini ] ; then cp /etc/php/$PHP_VER/mods-available/kopano.ini /etc/kopano/web ; fi && \
	ln -sf /etc/kopano/web/kopano.ini /etc/php/$PHP_VER/mods-available && \
	if [ -e /etc/php/$PHP_VER/mods-available/kopano_smime.ini ] ; then cp /etc/php/$PHP_VER/mods-available/kopano_smime.ini /etc/kopano/web ; fi && \
	ln -sf /etc/kopano/web/kopano_smime.ini /etc/php/$PHP_VER/mods-available && \
	cp /etc/php/$PHP_VER/fpm/pool.d/www.conf /etc/kopano/web && \
	ln -sf /etc/kopano/web/www.conf /etc/php/$PHP_VER/fpm/pool.d && \
	ln -sf /etc/kopano/web/kopano-web.conf /etc/nginx/conf.d/ && \
	ln -sf /etc/kopano/web/nginx.conf /etc/nginx && \
# move files to be exposed and mounted via synology to be copied over by init-script
	mv /etc/kopano /etc/kopano2copy && \
	mv /etc/z-push /etc/z-push2copy && \
	mv /var/spool/postfix /var/spool/postfix2copy && \
	mv /var/lib/amavis /var/lib/amavis2copy && \
	mv /var/lib/clamav /var/lib/clamav2copy && \
	mv /var/lib/postgrey /var/lib/postgrey2copy && \
	mv /var/lib/spamassassin /var/lib/spamassassin2copy && \
# remove kopano-logs as they will be mounted and initialised later
	rm -R /var/log/kopano && \
# entry-script, kopano scripts made executable
	chmod 700 /usr/local/bin/init.sh && \
	chmod 700 /usr/local/bin/kopano-postfix.sh && \
	chmod 700 /usr/local/bin/kopano-fetchmail.sh
# layer 4 steps 17,18 or 18,19: set workdir for backups later, entrypoint and expose ports
WORKDIR /var/lib/kopano/backup
ENTRYPOINT ["/usr/local/bin/init.sh"]
CMD ["alive"]
# ports kopano(s): 236/237, dagent-lmtp 2003, postfix 25, imap(s) 143/144/993/994, ical(s) 8080/8443, webmeetings 8090, Spreed 1935, STUN 3478
EXPOSE 236 237 2003 25 143 144 993 994 8080 8443 9080 9443 8090 1935 3478
