#!/bin/sh
# ** get common procedures, settings, tags and download urls
#echo "$(date '+%Y.%m.%d-%H:%M:%S') preupgrade" >> /tmp/inst.log
. "$(dirname $0)"/common
if [ ! -e "$ETC_PATH"/package.cfg ] ; then touch "$ETC_PATH"/package.cfg ; fi
. "$ETC_PATH"/package.cfg
if [ ! -n "$INSTALL_STATE" ] || [ "$INSTALL_STATE" != "completed" ]
then
	GUI_MESSAGE "No upgrade to previously uncompleted or legacy install. Please remove and install again. "
	exit 1
fi
# ** backup install-log & etc
SAVE_LOG_ETC
OLD_VER_TAG=$VER_TAG
GET_VER_TAG
if [ "$OLD_VER_TAG" != "$VER_TAG" ]
then
	DROP_OLD_DOCKER
	echo "$(date '+%Y.%m.%d-%H:%M:%S') preupgrade: drop docker $OLD_VER_TAG" >> /tmp/inst.log
fi
#echo "$(date '+%Y.%m.%d-%H:%M:%S') preupgrade done" >> /tmp/inst.log
exit 0

